name: 'Static analysis CI'
description: 'Static analysis CI'
inputs:
  lfs_sha:
    description: 'Cache LFS sha'
    required: true

runs:
  using: "composite"
  steps:

    - name: Check required inputs
      shell: bash
      run: |
        [[ "${{ inputs.lfs_sha }}" ]] || { echo "lfs_sha input is empty" ; exit 1; }

    # Needed for BUILD_TESTING
    - name: Copy LFS Data
      uses: ./source/.github/actions/lfs-copy
      with:
        lfs_sha: ${{ inputs.lfs_sha}}
        workflow_label: 'consumer'

    - name: Dependencies Dir
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        mkdir dependencies
        cd dependencies
        mkdir install

    - name: Install VTK dependencies
      uses: ./source/.github/actions/vtk-dependencies

    - name: Install VTK dependency
      uses: ./source/.github/actions/vtk-install-dep
      with:
        vtk_sha_file: ./source/.github/actions/vtk_commit_sha

    - name: Install F3D dependencies
      uses: ./source/.github/actions/f3d-dependencies

    - name: Setup Build Directory
      shell: bash
      working-directory: ${{github.workspace}}
      run: mkdir build

    # CMAKE_MODULE_PATH is required because of
    # https://github.com/AcademySoftwareFoundation/openvdb/issues/1160
    - name: Configure
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: >
        cmake ../source
        -Werror=dev
        -Werror=deprecated
        --warn-uninitialized
        -DBUILD_TESTING=ON
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_MODULE_PATH=$(pwd)/../dependencies/install/lib/cmake/OpenVDB/
        -DCMAKE_PREFIX_PATH:PATH=$(pwd)/../dependencies/install/
        -DF3D_MODULE_EXTERNAL_RENDERING=ON
        -DF3D_MODULE_EXR=ON
        -DF3D_PLUGIN_BUILD_ALEMBIC=ON
        -DF3D_PLUGIN_BUILD_ASSIMP=ON
        -DF3D_PLUGIN_BUILD_DRACO=ON
        -DF3D_PLUGIN_BUILD_OCCT=ON
        -DF3D_PLUGIN_BUILD_USD=ON
        -DF3D_PLUGIN_BUILD_VDB=ON
        -DF3D_STRICT_BUILD=ON
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    # It's necessary to run the build step to generate F3DIcon.h
    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --parallel 2

    - name: Clang-tidy
      shell: bash
      working-directory: ${{github.workspace}}/source
      run: run-clang-tidy -quiet -p ../build

    - name: Cppcheck
      shell: bash
      working-directory: ${{github.workspace}}/source
      run: >
        cppcheck -q
        --project=../build/compile_commands.json
        --enable=all
        --suppressions-list=.cppcheck.supp
        --error-exitcode=1
