name: "Install F3D dependencies"
description: "Install all F3D Dependencies but VTK"
inputs:
  versions_file:
    description: "File to recover versions from"
    required: true
  optional_deps_label:
    description: "Label to optional dependencies"
    required: false
    default: "optional-deps"
  cpu:
    description: "CPU architecture to build for"
    required: false
    default: "x86_64"

runs:
  using: "composite"
  steps:
    - name: Check required inputs
      shell: bash
      run: |
        [[ "${{ inputs.versions_file }}" ]] || { echo "versions_file is empty" ; exit 1; }

    - name: Dependencies Dir
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        mkdir dependencies
        cd dependencies
        mkdir install

    - name: Install VTK dependencies
      uses: ./source/.github/actions/vtk-dependencies
      with:
        versions_file: .github/workflows/versions.json
        cpu: ${{inputs.cpu}}

    - name: Install Raytracing Dependencies
      if: inputs.ospray_version != ''
      uses: ./source/.github/actions/ospray-sb-install-dep
      with:
        versions_file: .github/workflows/versions.json
        cpu: ${{inputs.cpu}}

    - name: Install F3D dependencies
      if: inputs.optional_deps_label == 'optional-deps'
      uses: ./source/.github/actions/f3d-dependencies
      with:
        versions_file: .github/workflows/versions.json
        cpu: ${{inputs.cpu}}
