name: "Install F3D dependencies"
description: "Install all F3D Dependencies but VTK"
inputs:
  versions_file:
    description: "File to recover versions from"
    required: true
  optdeps_label:
    description: "Label to flag for optional dependencies"
    required: false
    default: "optdeps"
  mindeps_label:
    description: "Label to flag for minimum versions dependencies"
    required: false
    default: "no-mindeps"
  cpu:
    description: "CPU architecture to build for"
    required: false
    default: "x86_64"

runs:
  using: "composite"
  steps:
    - name: Check required inputs
      shell: bash
      run: |
        [[ "${{ inputs.versions_file }}" ]] || { echo "versions_file is empty" ; exit 1; }

    - name: Install VTK dependencies
      uses: ./source/.github/actions/vtk-dependencies
      with:
        versions_file: ${{inputs.versions_file}}
        optdeps_label: ${{inputs.optdeps_label}}
        mindeps_label: ${{inputs.mindeps_label}}
        cpu: ${{inputs.cpu}}

    - name: Install F3D dependencies
      if: inputs.optdeps_label == 'optdeps'
      uses: ./source/.github/actions/f3d-dependencies
      with:
        versions_file: ${{inputs.versions_file}}
        mindeps_label: ${{inputs.mindeps_label}}
        cpu: ${{inputs.cpu}}
