name: 'External build CI'
description: 'External build CI'
inputs:
  openvdb_version:
    description: 'Version of openvdb to build'
    required: true

runs:
  using: "composite"
  steps:

    - name: Create top level CMakeLists.txt
      shell: bash
      working-directory: ${{github.workspace}}
      run: echo -e "cmake_minimum_required(VERSION 3.21)\nproject(toplevel)\nadd_subdirectory(f3d)" > source/CMakeLists.txt

    - name: Dependencies Dir
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        mkdir dependencies
        cd dependencies
        mkdir install

    - name: Install VTK dependencies
      uses: ./source/f3d/.github/actions/vtk-dependencies
      with:
        source_dir: ./source/f3d
        openvdb_version: ${{inputs.openvdb_version}}
 
    - name: Install VTK dependency
      uses: ./source/f3d/.github/actions/vtk-install-dep
      with:
        vtk_sha_file: ./source/f3d/.github/actions/vtk_commit_sha
        openvdb_version: ${{inputs.openvdb_version}}

    - name: Setup Build Directory
      shell: bash
      working-directory: ${{github.workspace}}
      run: mkdir build

    - name: Configure
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: >
        cmake ../source
        -Werror=dev
        -Werror=deprecated
        --warn-uninitialized
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_PREFIX_PATH:PATH=$(pwd)/../dependencies/install/
        -DF3D_STRICT_BUILD=ON
        -DF3D_MODULE_UI=OFF

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --parallel 2
