name: "External build CI"
description: "External build CI"
inputs:
  versions_file:
    description: "File to recover versions from"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check required inputs
      shell: bash
      run: |
        [[ "${{ inputs.versions_file }}" ]] || { echo "versions_file is empty" ; exit 1; }

    - name: Create top level CMakeLists.txt
      shell: bash
      working-directory: ${{github.workspace}}
      run: echo -e "cmake_minimum_required(VERSION 3.21)\nproject(toplevel)\nadd_subdirectory(f3d)" > source/CMakeLists.txt

    - name: Install VTK dependencies
      uses: ./source/f3d/.github/actions/vtk-dependencies
      with:
        source_dir: ./source/f3d
        versions_file: ${{inputs.versions_file}}
        optdeps_label: no-optdeps

    - name: Install VTK dependency
      uses: ./source/f3d/.github/actions/vtk-install-dep
      with:
        versions_file: ${{inputs.versions_file}}
        optdeps_label: no-optdeps

    - name: Setup Build Directory
      shell: bash
      working-directory: ${{github.workspace}}
      run: mkdir build

    - name: Configure
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: >
        cmake ../source
        -Werror=dev
        -Werror=deprecated
        --warn-uninitialized
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_PREFIX_PATH:PATH=$(pwd)/../dependencies/install/
        -DF3D_STRICT_BUILD=ON
        -DF3D_MODULE_UI=OFF
        -DF3D_MODULE_CLIP=OFF

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --parallel 2
