name: 'Install Boost Dependency'
description: 'Install Boost Dependency using cache when possible'

runs:
  using: "composite"
  steps:

    - name: Cache Boost
      id: cache-boost
      uses: actions/cache@v3
      with:
        path: dependencies/boost_install
        key: boost-1.82.0-${{runner.os}}-0

    - name: Checkout Boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: boostorg/boost
        submodules: true
        fetch-depth: 0
        path: './dependencies/boost'
        ref: boost-1.82.0

    - name: Setup Boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies
      shell: bash
      run: |
        mkdir boost_build
        mkdir boost_install

    - name: Configure Boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/boost
      shell: bash
      run: ./bootstrap.sh

    - name: Build Boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/boost
      shell: bash
      run: >
        ./b2
        --prefix='../boost_install'
        --build-dir='../boost_build'
        variant='release'
        link=static
        runtime-link=shared
        --with-date_time
        --with-filesystem
        --with-program_options
        --with-regex
        --with-system
        install

    - name: Copy to install
      working-directory: ${{github.workspace}}/dependencies/boost_install
      shell: bash
      run: cp -r ./* ../install/
