name: "Install webifc Dependency"
description: "Install webifc Dependency using cache when possible"
inputs:
  cpu:
    description: "CPU architecture to build for"
    required: false
    default: "x86_64"
  version:
    description: "Version of webifc to build"
    required: true
  global_cache_index:
    description: "Global cache index"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check required inputs
      shell: bash
      run: |
        [[ "${{ inputs.version }}" ]] || { echo "version input is empty" ; exit 1; }
        [[ "${{ inputs.global_cache_index }}" ]] || { echo "global_cache_index input is empty" ; exit 1; }

    - name: Cache webifc
      id: cache-webifc
      uses: actions/cache/restore@v4
      with:
        path: dependencies/webifc_install
        key: webifc-${{inputs.version}}-${{runner.os}}-${{inputs.cpu}}-${{inputs.global_cache_index}}-0

    - name: Checkout webifc
      if: steps.cache-webifc.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: ThatOpen/engine_web-ifc
        path: "./dependencies/webifc"
        ref: ${{inputs.version}}

    - name: Setup webifc
      if: steps.cache-webifc.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies
      shell: bash
      run: |
        mkdir webifc_build
        mkdir webifc_install

    - name: Configure webifc
      if: steps.cache-webifc.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/webifc_build
      shell: bash
      run: >
        cmake ../webifc/src/cpp
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        -DCMAKE_INSTALL_PREFIX=../webifc_install
        ${{ runner.os == 'macOS' && '-DCMAKE_OSX_DEPLOYMENT_TARGET=13.3' || null }}
        ${{ runner.os == 'Windows' && '-Ax64 -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL' || null }}

    - name: Build and install webifc
      if: steps.cache-webifc.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/webifc_build
      shell: bash
      run: cmake --build . --parallel 2 --target install --config Release

    - name: Copy to install
      working-directory: ${{github.workspace}}/dependencies/webifc_install
      shell: bash
      run: cp -r ./* ../install/

    - name: Save cache
      if: steps.cache-webifc.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        key: ${{ steps.cache-webifc.outputs.cache-primary-key }}
        path: dependencies/webifc_install
