name: "Install VTK Dependency"
description: "Install VTK Dependency using cache when possible"
inputs:
  versions_file:
    description: "File to recover versions from"
    required: true
  optdeps_label:
    description: "Label to flag for optional dependencies"
    required: false
    default: "optdeps"
  mindeps_label:
    description: "Label to flag for minimum versions dependencies"
    required: false
    default: "no-mindeps"
  vtk_version:
    description: "VTK version, either a hash/tag, or 'commit', which means recover from versions.json"
    required: false
    default: "commit"
  cpu:
    description: "CPU architecture to build for"
    required: false
    default: "x86_64"

runs:
  using: "composite"
  steps:
    - name: Check required inputs
      shell: bash
      run: |
        [[ "${{inputs.versions_file}}" ]] || { echo "versions_file is empty" ; exit 1; }

    - name: Recover VTK version if needed
      if: inputs.vtk_version == 'commit'
      id: vtk_ver
      uses: f3d-app/extract-version-action@main
      with:
        file: ${{inputs.versions_file}}
        special_name: vtk_commit_sha

    - name: Store VTK version in env
      if: inputs.vtk_version == 'commit'
      shell: bash
      run: echo "VTK_VERSION=${{steps.vtk_ver.outputs.extract}}" >> $GITHUB_ENV

    - name: Store VTK version in env from the input directly
      if: inputs.vtk_version != 'commit'
      shell: bash
      run: echo "VTK_VERSION=${{inputs.vtk_version}}" >> $GITHUB_ENV

    - name: Extract zlib version
      id: zlib_ver
      uses: f3d-app/extract-version-action@main
      with:
        file: ${{inputs.versions_file}}
        name: zlib
        minver_label: ${{inputs.mindeps_label == 'mindeps' && 'minver' || ''}}

    - name: Extract blosc version
      id: blosc_ver
      uses: f3d-app/extract-version-action@main
      with:
        file: ${{inputs.versions_file}}
        name: blosc
        minver_label: ${{inputs.mindeps_label == 'mindeps' && 'minver' || ''}}

    - name: Extract tbb version
      id: tbb_ver
      uses: f3d-app/extract-version-action@main
      with:
        file: ${{inputs.versions_file}}
        name: tbb
        minver_label: ${{inputs.mindeps_label == 'mindeps' && 'minver' || ''}}

    - name: Extract openvdb version
      if: inputs.optdeps_label == 'optdeps'
      id: openvdb_ver
      uses: f3d-app/extract-version-action@main
      with:
        file: ${{inputs.versions_file}}
        name: openvdb
        minver_label: ${{inputs.mindeps_label == 'mindeps' && 'minver' || ''}}

    - name: Extract ospray version
      if: inputs.optdeps_label == 'optdeps'
      id: ospray_ver
      uses: f3d-app/extract-version-action@main
      with:
        file: ${{inputs.versions_file}}
        name: ospray
        minver_label: ${{inputs.mindeps_label == 'mindeps' && 'minver' || ''}}

    - name: Extract curl version
      if: inputs.optdeps_label == 'optdeps'
      id: curl_ver
      uses: f3d-app/extract-version-action@main
      with:
        file: ${{inputs.versions_file}}
        name: curl
        minver_label: ${{inputs.mindeps_label == 'mindeps' && 'minver' || ''}}

    - name: Extract gdal version
      if: inputs.optdeps_label == 'optdeps'
      id: gdal_ver
      uses: f3d-app/extract-version-action@main
      with:
        file: ${{inputs.versions_file}}
        name: gdal
        minver_label: ${{inputs.mindeps_label == 'mindeps' && 'minver' || ''}}

    - name: Extract geotiff version
      if: inputs.optdeps_label == 'optdeps'
      id: geotiff_ver
      uses: f3d-app/extract-version-action@main
      with:
        file: ${{inputs.versions_file}}
        name: geotiff
        minver_label: ${{inputs.mindeps_label == 'mindeps' && 'minver' || ''}}

    - name: Extract pdal version
      if: inputs.optdeps_label == 'optdeps'
      id: pdal_ver
      uses: f3d-app/extract-version-action@main
      with:
        file: ${{inputs.versions_file}}
        name: pdal
        minver_label: ${{inputs.mindeps_label == 'mindeps' && 'minver' || ''}}

    - name: Extract proj version
      if: inputs.optdeps_label == 'optdeps'
      id: proj_ver
      uses: f3d-app/extract-version-action@main
      with:
        file: ${{inputs.versions_file}}
        name: proj
        minver_label: ${{inputs.mindeps_label == 'mindeps' && 'minver' || ''}}

    - name: Extract sqlite_csb version
      if: inputs.optdeps_label == 'optdeps'
      id: sqlite_csb_ver
      uses: f3d-app/extract-version-action@main
      with:
        file: ${{inputs.versions_file}}
        name: sqlite_csb
        minver_label: ${{inputs.mindeps_label == 'mindeps' && 'minver' || ''}}

    - name: Extract tiff version
      if: inputs.optdeps_label == 'optdeps'
      id: tiff_ver
      uses: f3d-app/extract-version-action@main
      with:
        file: ${{inputs.versions_file}}
        name: tiff
        minver_label: ${{inputs.mindeps_label == 'mindeps' && 'minver' || ''}}

    - name: Extract global cache index
      id: global_idx
      uses: f3d-app/extract-version-action@main
      with:
        file: ${{inputs.versions_file}}
        special_name: global_cache_index

    - name: Cache VTK
      id: cache-vtk
      uses: actions/cache/restore@v5
      with:
        path: dependencies/vtk_install
        key: vtk-${{env.VTK_VERSION}}-${{steps.zlib_ver.outputs.extract}}-${{steps.blosc_ver.outputs.extract}}-${{steps.tbb_ver.outputs.extract}}${{ steps.openvdb_ver.outputs.extract != '' && format('-openvdb-{0}', steps.openvdb_ver.outputs.extract) || '' }}${{ steps.ospray_ver.outputs.extract != '' && format('-ospray-{0}', steps.ospray_ver.outputs.extract) || '' }}${{ steps.curl_ver.outputs.extract != '' && format('-curl-{0}', steps.curl_ver.outputs.extract) || '' }}${{ steps.gdal_ver.outputs.extract != '' && format('-gdal-{0}', steps.gdal_ver.outputs.extract) || '' }}${{ steps.geotiff_ver.outputs.extract != '' && format('-geotiff-{0}', steps.geotiff_ver.outputs.extract) || '' }}${{ steps.pdal_ver.outputs.extract != '' && format('-pdal-{0}', steps.pdal_ver.outputs.extract) || '' }}${{ steps.proj_ver.outputs.extract != '' && format('-proj-{0}', steps.proj_ver.outputs.extract) || '' }}${{ steps.sqlite_csb_ver.outputs.extract != '' && format('-sqlite-{0}', steps.sqlite_csb_ver.outputs.extract) || '' }}${{ steps.tiff_ver.outputs.extract != '' && format('-tiff-{0}', steps.tiff_ver.outputs.extract) || '' }}-${{runner.os}}-${{inputs.cpu}}-${{steps.global_idx.outputs.extract}}-5

    - name: Setup VTK
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies
      shell: bash
      run: |
        mkdir vtk_build
        mkdir vtk_install

    # MacOS needs fetch-depth: 0 to avoid an issue with version in linker
    - name: Checkout VTK
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      uses: actions/checkout@v6
      with:
        repository: Kitware/VTK
        submodules: true
        fetch-depth: 0
        path: "./dependencies/vtk"
        ref: ${{env.VTK_VERSION}}

    # CMake 3.31 introduced a new policy producing a warning when using vtkModule.cmake
    # See https://gitlab.kitware.com/vtk/vtk/-/issues/19526
    - name: Patch VTK CMake
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/vtk
      shell: bash
      run: |
        cat $GITHUB_ACTION_PATH/set_cmp0177_policy.cmake CMake/vtkModule.cmake > patched.cmake
        mv patched.cmake CMake/vtkModule.cmake

      # OpenVDB_CMAKE_PATH is required because of
      # https://github.com/AcademySoftwareFoundation/openvdb/issues/1160 and
      # https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10393
      # CMAKE_MODULE_PATH is not used because OpenVDB_CMAKE_PATH seems to be the canonical way to handle this with VTK
    - name: Configure VTK
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/vtk_build
      shell: bash
      run: >
        cmake ../vtk
        -DBUILD_SHARED_LIBS=ON
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX:PATH=../vtk_install
        -DCMAKE_PREFIX_PATH:PATH=$(pwd)/../install/
        -DOpenVDB_CMAKE_PATH=${{ inputs.optdeps_label == 'optdeps' && '$(pwd)/../install/lib/cmake/OpenVDB/' || '' }}
        -DVTKOSPRAY_ENABLE_DENOISER=ON
        -DVTK_BUILD_TESTING=OFF
        -DVTK_DEBUG_LEAKS=ON
        -DVTK_ENABLE_LOGGING=OFF
        -DVTK_ENABLE_OSPRAY=ON
        -DVTK_ENABLE_REMOTE_MODULES=OFF
        -DVTK_ENABLE_WRAPPING=OFF
        -DVTK_GROUP_ENABLE_Rendering=DEFAULT
        -DVTK_GROUP_ENABLE_StandAlone=DEFAULT
        -DVTK_LEGACY_REMOVE=ON
        -DVTK_MODULE_ENABLE_VTK_CommonSystem=YES
        -DVTK_MODULE_ENABLE_VTK_FiltersGeneral=YES
        -DVTK_MODULE_ENABLE_VTK_FiltersGeometry=YES
        -DVTK_MODULE_ENABLE_VTK_IOCityGML=YES
        -DVTK_MODULE_ENABLE_VTK_IOExodus=YES
        -DVTK_MODULE_ENABLE_VTK_IOGeometry=YES
        -DVTK_MODULE_ENABLE_VTK_IOHDF=YES
        -DVTK_MODULE_ENABLE_VTK_IOImage=YES
        -DVTK_MODULE_ENABLE_VTK_IOImport=YES
        -DVTK_MODULE_ENABLE_VTK_IOLegacy=YES
        -DVTK_MODULE_ENABLE_VTK_IONetCDF=YES
        -DVTK_MODULE_ENABLE_VTK_IOOpenVDB=${{ inputs.optdeps_label == 'optdeps' && 'YES' || 'DEFAULT' }}
        -DVTK_MODULE_ENABLE_VTK_IOPDAL=${{ inputs.optdeps_label == 'optdeps' && 'YES' || 'DEFAULT' }}
        -DVTK_MODULE_ENABLE_VTK_IOPLY=YES
        -DVTK_MODULE_ENABLE_VTK_IOXML=YES
        -DVTK_MODULE_ENABLE_VTK_ImagingCore=YES
        -DVTK_MODULE_ENABLE_VTK_ImagingHybrid=YES
        -DVTK_MODULE_ENABLE_VTK_InteractionStyle=YES
        -DVTK_MODULE_ENABLE_VTK_InteractionWidgets=YES
        -DVTK_MODULE_ENABLE_VTK_RenderingAnnotation=YES
        -DVTK_MODULE_ENABLE_VTK_RenderingCore=YES
        -DVTK_MODULE_ENABLE_VTK_RenderingGridAxes=YES
        -DVTK_MODULE_ENABLE_VTK_RenderingOpenGL2=YES
        -DVTK_MODULE_ENABLE_VTK_RenderingRayTracing=${{ inputs.optdeps_label == 'optdeps' && 'YES' || 'DEFAULT' }}
        -DVTK_MODULE_ENABLE_VTK_RenderingVolumeOpenGL2=YES
        -DVTK_MODULE_ENABLE_VTK_TestingCore=YES
        -DVTK_OPENGL_HAS_EGL=${{ runner.os != 'macOS' && 'ON' || 'OFF' }}
        -DVTK_SMP_IMPLEMENTATION_TYPE=TBB
        -DVTK_VERSIONED_INSTALL=OFF
        ${{ runner.os == 'macOS' && '-DCMAKE_OSX_DEPLOYMENT_TARGET=14.0' || null }}
        ${{ runner.os == 'Windows' && '-Ax64 -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL' || null }}

    - name: Build VTK
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/vtk_build
      shell: bash
      run: cmake --build . --parallel 2 --target install --config Release

    - name: Copy to install
      working-directory: ${{github.workspace}}/dependencies/vtk_install
      shell: bash
      run: cp -r ./* ../install/

    - name: Save cache
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        key: ${{ steps.cache-vtk.outputs.cache-primary-key }}
        path: dependencies/vtk_install
