name: 'Install OCCT Dependency'
description: 'Install OCCT Dependency using cache when possible'
inputs:
  os:
    description: 'OS to build on'
    required: false
    default: 'ubuntu-latest'
runs:
  using: "composite"
  steps:

    - name: Cache OCCT
      id: cache-occt
      uses: actions/cache@v3
      with:
        path: dependencies/occt_install
        key: occt-V7_6_0-${{inputs.os}}-0

    - name: Checkout OCCT
      if: steps.cache-occt.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: Open-Cascade-SAS/OCCT
        submodules: 'true'
        path: './dependencies/occt'
        ref: V7_6_0

    - name: Setup OCCT
      if: steps.cache-occt.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies
      shell: bash
      run: |
        mkdir occt_build
        mkdir occt_install

    - name: Configure OCCT
      if: steps.cache-occt.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/occt_build
      shell: bash
      run: >
        cmake ../occt
        -DBUILD_LIBRARY_TYPE=Static
        -DBUILD_ADDITIONAL_TOOLKITS="TKSTEP;TKIGES;TKMesh"
        -DBUILD_MODULE_ApplicationFramework=OFF
        -DBUILD_MODULE_DataExchange=OFF
        -DBUILD_MODULE_Draw=OFF
        -DBUILD_MODULE_FoundationClasses=OFF
        -DBUILD_MODULE_ModelingAlgorithms=OFF
        -DBUILD_MODULE_ModelingData=OFF
        -DBUILD_MODULE_Visualization=OFF
        -DBUILD_DOC_Overview=OFF
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX:PATH=../occt_install
        ${{ inputs.os == 'macos-latest' && '-DCMAKE_OSX_DEPLOYMENT_TARGET=10.15' || null }}
        ${{ inputs.os == 'windows-latest' && '-Ax64 -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded' || null }}

    - name: Build OCCT
      if: steps.cache-occt.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/occt_build
      shell: bash
      run: cmake --build . --parallel 2 --target install --config Release

    - name: Patch OCCT install macos
      if: |
        steps.cache-occt.outputs.cache-hit != 'true' &&
        inputs.os == 'macos-latest'
      working-directory: ${{github.workspace}}/dependencies
      shell: bash
      run: sed -i '' 's/OpenCASCADE_LIBRARIES [A-Za-z0-9;]\+/OpenCASCADE_LIBRARIES TKSTEP;TKSTEPAttr;TKSTEP209;TKSTEPBase;TKIGES;TKBool;TKMesh;TKXSBase;TKBO;TKPrim;TKShHealing;TKTopAlgo;TKBRep;TKGeomAlgo;TKGeomBase;TKG3d;TKG2d;TKMath;TKernel/' occt_install/lib/cmake/opencascade/OpenCASCADEConfig.cmake

    - name: Patch OCCT install ubuntu
      if: |
        steps.cache-occt.outputs.cache-hit != 'true' &&
        inputs.os == 'ubuntu-latest'
      working-directory: ${{github.workspace}}/dependencies
      shell: bash
      run: sed -i 's/OpenCASCADE_LIBRARIES [A-Za-z0-9;]\+/OpenCASCADE_LIBRARIES TKSTEP;TKSTEPAttr;TKSTEP209;TKSTEPBase;TKIGES;TKBool;TKMesh;TKXSBase;TKBO;TKPrim;TKShHealing;TKTopAlgo;TKBRep;TKGeomAlgo;TKGeomBase;TKG3d;TKG2d;TKMath;TKernel/' occt_install/lib/cmake/opencascade/OpenCASCADEConfig.cmake

    - name: Copy to install
      working-directory: ${{github.workspace}}/dependencies/occt_install
      shell: bash
      run: cp -r ./* ../install/
