name: "Install x264 Dependency"
description: "Install x264 Dependency using cache when possible"
inputs:
  versions_file:
    description: "File to recover versions from"
    required: true
  mindeps_label:
    description: "Label to flag for minimum versions dependencies"
    required: false
    default: "no-mindeps"
  cpu:
    description: "CPU architecture to build for"
    required: false
    default: "x86_64"

runs:
  using: "composite"
  steps:
    - name: Check required inputs
      shell: bash
      run: |
        [[ "${{inputs.versions_file}}" ]] || { echo "versions_file is empty" ; exit 1; }

    - name: Extract x264 version
      id: x264_ver
      uses: f3d-app/extract-version-action@main
      with:
        file: ${{inputs.versions_file}}
        name: x264
        minver_label: ${{inputs.mindeps_label == 'mindeps' && 'minver' || ''}}

    - name: Extract global cache index
      id: global_idx
      uses: f3d-app/extract-version-action@main
      with:
        file: ${{inputs.versions_file}}
        special_name: global_cache_index

    - name: Cache x264
      id: cache-x264
      continue-on-error: true # https://github.com/actions/cache/issues/1754
      uses: actions/cache/restore@v6
      with:
        path: dependencies/x264_install
        key: x264-${{steps.x264_ver.outputs.extract}}-${{runner.os}}-${{inputs.cpu}}-${{steps.global_idx.outputs.extract}}-0

    # Dependents: ffmpeg
    - name: Checkout x264
      if: steps.cache-x264.outputs.cache-hit != 'true'
      shell: bash
      run: |
        git clone https://code.videolan.org/videolan/x264.git dependencies/x264
        cd dependencies/x264
        git checkout ${{steps.x264_ver.outputs.extract}}

    - name: Setup x264
      if: steps.cache-x264.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies
      shell: bash
      run: mkdir x264_install

    - name: Setup MSVC (Windows)
      if: steps.cache-x264.outputs.cache-hit != 'true' && runner.os == 'Windows'
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: x64

    # Build x264 as static library to be used by ffmpeg, otherwise we can have RPATH issues
    - name: Configure x264
      if: steps.cache-x264.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/x264
      shell: bash
      env:
        CC: ${{ runner.os == 'Windows' && 'cl' || runner.os == 'macOS' && 'clang' || 'gcc' }}
        MACOSX_DEPLOYMENT_TARGET: 14.0
      run: >
        ./configure
        --enable-static
        --enable-pic
        --disable-asm
        --disable-cli
        --disable-opencl
        --disable-lavf
        --disable-swscale
        --prefix=../x264_install

    - name: Build x264
      if: steps.cache-x264.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/x264
      shell: bash
      run: make -j2 install

    - name: Copy to install
      working-directory: ${{github.workspace}}/dependencies/x264_install
      shell: bash
      run: cp -r ./* ../install/

    - name: Save cache
      if: steps.cache-x264.outputs.cache-hit != 'true'
      uses: actions/cache/save@v6
      with:
        key: ${{ steps.cache-x264.outputs.cache-primary-key }}
        path: dependencies/x264_install
