name: 'Install Imath Dependency'
description: 'Install Imath Dependency using cache when possible'
inputs:
  cpu:
    description: 'CPU architecture to build for'
    required: false
    default: 'x86_64'

runs:
  using: "composite"
  steps:

    - name: Cache Imath
      id: cache-imath
      uses: actions/cache@v4
      with:
        path: dependencies/imath_install
        key: imath-v3.1.10-${{runner.os}}-${{inputs.cpu}}-1

    # Dependents: alembic
    - name: Checkout Imath
      if: steps.cache-imath.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: AcademySoftwareFoundation/Imath
        path: './dependencies/imath'
        ref: v3.1.10

    - name: Setup Imath
      if: steps.cache-imath.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies
      shell: bash
      run: |
        mkdir imath_build
        mkdir imath_install

    - name: Configure Imath
      if: steps.cache-imath.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/imath_build
      shell: bash
      run: >
        cmake ../imath
        -DBUILD_SHARED_LIBS=ON
        -DBUILD_TESTING=OFF
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX:PATH=../imath_install
        -DCMAKE_OSX_ARCHITECTURES=${{ inputs.cpu }}
        ${{ runner.os == 'macOS' && '-DCMAKE_OSX_DEPLOYMENT_TARGET=10.15' || null }}
        ${{ runner.os == 'Windows' && '-Ax64 -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL' || null }}

    - name: Build Imath
      if: steps.cache-imath.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/imath_build
      shell: bash
      run: cmake --build . --parallel 2 --target install --config Release

    - name: Copy to install
      working-directory: ${{github.workspace}}/dependencies/imath_install
      shell: bash
      run: cp -r ./* ../install/
