name: 'Install mesa EGL Dependency'
description: 'Install mesa with EGL support using cache when possible'
runs:
  using: "composite"
  steps:

    - name: Cache mesa
      id: cache-mesa
      uses: actions/cache@v3
      with:
        path: dependencies/mesa_install
        key: mesa-v2.7.1-${{runner.os}}-0

    - name: Checkout mesa
      if: steps.cache-mesa.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: Mesa3D/mesa
        path: './dependencies/mesa'
        ref: mesa-22.3.7

    - name: Setup mesa
      if: steps.cache-mesa.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies
      shell: bash
      run: |
        mkdir mesa_build
        mkdir mesa_install

    - name: Configure mesa
      if: steps.cache-mesa.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/mesa
      shell: bash
      run: >
        meson setup ../build
          -D egl=enabled
          -D gles1=enabled
          -D gles2=enabled
          -D platforms=x11
          -Dprefix=$(pwd)/../mesa_install/

    - name: Build and install mesa
      if: steps.cache-mesa.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/mesa_build
      shell: bash
      run: ninja install

    - name: Copy to install
      working-directory: ${{github.workspace}}/dependencies/mesa_install
      shell: bash
      run: cp -r ./* ../install/
