name: "Install ffmpeg Dependency"
description: "Install ffmpeg Dependency using cache when possible"
inputs:
  versions_file:
    description: "File to recover versions from"
    required: true
  mindeps_label:
    description: "Label to flag for minimum versions dependencies"
    required: false
    default: "no-mindeps"
  cpu:
    description: "CPU architecture to build for"
    required: false
    default: "x86_64"

runs:
  using: "composite"
  steps:
    - name: Check required inputs
      shell: bash
      run: |
        [[ "${{inputs.versions_file}}" ]] || { echo "versions_file is empty" ; exit 1; }

    - name: Extract ffmpeg version
      id: ffmpeg_ver
      uses: f3d-app/extract-version-action@main
      with:
        file: ${{inputs.versions_file}}
        name: ffmpeg
        minver_label: ${{inputs.mindeps_label == 'mindeps' && 'minver' || ''}}

    - name: Extract x264 version
      id: x264_ver
      uses: f3d-app/extract-version-action@main
      with:
        file: ${{inputs.versions_file}}
        name: x264
        minver_label: ${{inputs.mindeps_label == 'mindeps' && 'minver' || ''}}

    - name: Extract global cache index
      id: global_idx
      uses: f3d-app/extract-version-action@main
      with:
        file: ${{inputs.versions_file}}
        special_name: global_cache_index

    - name: Cache ffmpeg
      id: cache-ffmpeg
      continue-on-error: true # https://github.com/actions/cache/issues/1754
      uses: actions/cache/restore@v6
      with:
        path: dependencies/ffmpeg_install
        key: ffmpeg-${{steps.ffmpeg_ver.outputs.extract}}-${{ steps.x264_ver.outputs.extract }}-${{runner.os}}-${{inputs.cpu}}-${{steps.global_idx.outputs.extract}}-0

    - name: Checkout ffmpeg
      if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
      uses: actions/checkout@v7
      with:
        repository: FFmpeg/FFmpeg
        path: "./dependencies/ffmpeg"
        ref: ${{steps.ffmpeg_ver.outputs.extract}}

    - name: Setup ffmpeg
      if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies
      shell: bash
      run: mkdir ffmpeg_install

    - name: Setup MSVC (Windows)
      if: steps.cache-ffmpeg.outputs.cache-hit != 'true' && runner.os == 'Windows'
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: x64

    # Required to find x264
    - name: Install pkg-config
      if: steps.cache-ffmpeg.outputs.cache-hit != 'true' && runner.os == 'Windows'
      shell: bash
      run: choco install pkgconfiglite -y

    # There is a bug in ffmpeg configure when generating dependency files on Windows with MSVC.
    # Dependency files are not necessary for CI build so they are patched out.
    # https://trac.ffmpeg.org/ticket/9043
    - name: Patch ffmpeg configure to disable MSVC dependency-file generation (Windows)
      if: steps.cache-ffmpeg.outputs.cache-hit != 'true' && runner.os == 'Windows'
      working-directory: ${{github.workspace}}/dependencies/ffmpeg
      shell: bash
      run: sed -i "/_DEPCMD='.*awk/s/.*/            _DEPCMD='true'/" configure

    - name: Configure ffmpeg
      if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/ffmpeg
      shell: bash
      env:
        PKG_CONFIG_PATH: ${{github.workspace}}/dependencies/install/lib/pkgconfig
        CC: ${{ runner.os == 'Windows' && 'cl' || runner.os == 'macOS' && 'clang' || 'gcc' }}
        MACOSX_DEPLOYMENT_TARGET: 14.0
      run: >
        ./configure
        --enable-gpl
        --enable-shared
        --disable-static
        --disable-all
        --disable-x86asm
        --enable-libx264
        --enable-encoder=libx264
        --enable-avcodec
        --enable-avutil
        --prefix=../ffmpeg_install
        ${{ runner.os == 'Windows' && '--toolchain=msvc' || '' }}
        ${{ runner.os == 'macOS' && '--install-name-dir=@rpath' || '' }}

    - name: Build ffmpeg
      if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/ffmpeg
      shell: bash
      run: make -j2 install-libs install-headers

    - name: Copy to install
      working-directory: ${{github.workspace}}/dependencies/ffmpeg_install
      shell: bash
      run: cp -r ./* ../install/

    - name: Save cache
      if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
      uses: actions/cache/save@v6
      with:
        key: ${{ steps.cache-ffmpeg.outputs.cache-primary-key }}
        path: dependencies/ffmpeg_install
