name: "WebAssembly CI"
description: "WebAssembly CI"
inputs:
  timestamp:
    description: "Docker image timestamp"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/source/webassembly
      run: npm run build

    - name: Run Xvfb
      shell: bash
      run: Xvfb $DISPLAY -screen 0 1280x1024x24 &

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/source/webassembly
      run: npm test

    - name: Pack
      shell: bash
      working-directory: ${{github.workspace}}/source/webassembly
      run: npm pack

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        path: ./source/webassembly/f3d-*.tgz
        name: f3d-wasm-package
