name: "WebAssembly CI"
description: "WebAssembly CI"

runs:
  using: "composite"
  steps:
    - name: Build and pack
      shell: bash
      working-directory: ${{github.workspace}}/source/webassembly
      run: npm pack

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/source/webassembly
      run: npm test

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        path: ./source/webassembly/f3d-*.tgz
        name: f3d-wasm-package
