name: "WebAssembly CI"
description: "WebAssembly CI"
inputs:
  lfs_sha:
    description: "Cache LFS sha"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check required inputs
      shell: bash
      run: |
        [[ "${{ inputs.lfs_sha }}" ]] || { echo "lfs_sha input is empty" ; exit 1; }

    - name: Recover LFS Data
      uses: f3d-app/lfs-data-cache-action@v2
      with:
        type: "consumer"
        lfs_sha: ${{inputs.lfs_sha}}
        cache_postfix: cache-0

    - name: Build and pack
      shell: bash
      working-directory: ${{github.workspace}}/source
      run: npm pack

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/source
      run: npm test

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        path: ./source/f3d-*.tgz
        name: f3d-wasm-package
