name: 'Python specific CI'
description: 'Python specific CI'

runs:
  using: "composite"
  steps:

    - name: Dependencies Dir
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        mkdir dependencies
        cd dependencies
        mkdir install

    - name: Install TBB
      uses: ./source/.github/actions/tbb-install-dep

    - name: Install VTK dependency
      uses: ./source/.github/actions/vtk-install-dep
      with:
        vtk_sha_file: ./source/.github/actions/vtk_commit_sha

    - name: Install F3D dependencies
      uses: ./source/.github/actions/f3d-dependencies

    - name: Set PATH windows
      if: runner.os == 'Windows'
      shell: powershell
      working-directory: ${{github.workspace}}
      run: echo "PATH=$env:PATH;$(pwd)\dependencies\install\bin\;$(pwd)\install\bin\;"| Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Set CMAKE_PREFIX_PATH
      shell: bash
      working-directory: ${{github.workspace}}/dependencies/install
      run: echo "CMAKE_PREFIX_PATH=$(pwd)" >> $GITHUB_ENV

    - name: Escaping backslashes Windows
      if: runner.os == 'Windows'
      shell: bash
      run: echo "ESCAPED_WS=${{github.workspace}}" | tr '\\' '/' >> $GITHUB_ENV

    - name: Set SKBUILD_CMAKE_ARGS
      shell: bash
      run: >
        echo "SKBUILD_CMAKE_ARGS=-DF3D_DEPENDENCIES_DIR=${{ env.ESCAPED_WS }}/dependencies/install/bin;
        -DF3D_PLUGIN_BUILD_ALEMBIC=ON;
        -DF3D_PLUGIN_BUILD_ASSIMP=ON;
        -DF3D_PLUGIN_BUILD_DRACO=ON;
        -DF3D_PLUGIN_BUILD_OCCT=ON;
        -DF3D_PLUGIN_OCCT_COLORING_SUPPORT=ON;
        -DF3D_MODULE_EXR=ON;
        -DF3D_MODULE_EXTERNAL_RENDERING=ON" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Build wheel
      shell: bash
      working-directory: ${{github.workspace}}/source
      run: python -m pip -v wheel .

    - name: Upload Tests Artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./source/*.whl
        name: ${{runner.os}}-wheel
