name: 'Python specific CI'
description: 'Python specific CI'
inputs:
  lfs_sha:
    description: 'Cache LFS sha'
    required: true

runs:
  using: "composite"
  steps:

    - name: Check required inputs
      shell: bash
      run: |
        [[ "${{ inputs.lfs_sha }}" ]] || { echo "lfs_sha input is empty" ; exit 1; }

    - name: Copy LFS Data
      uses: ./source/.github/actions/lfs-copy
      with:
        lfs_sha: ${{ inputs.lfs_sha}}
        workflow_label: 'consumer'

    - name: Dependencies Dir
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        mkdir dependencies
        cd dependencies
        mkdir install

    - name: Install VTK dependencies
      uses: ./source/.github/actions/vtk-dependencies

    - name: Install VTK dependency
      uses: ./source/.github/actions/vtk-install-dep
      with:
        vtk_sha_file: ./source/.github/actions/vtk_commit_sha

    - name: Install F3D dependencies
      uses: ./source/.github/actions/f3d-dependencies

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest==8.0.0

    - name: Set PATH windows
      if: runner.os == 'Windows'
      shell: powershell
      working-directory: ${{github.workspace}}
      run: echo "PATH=$env:PATH;$(pwd)\dependencies\install\bin\;$(pwd)\install\bin\;"| Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Set CMAKE_PREFIX_PATH
      shell: bash
      working-directory: ${{github.workspace}}/dependencies/install
      run: echo "CMAKE_PREFIX_PATH=$(pwd)" >> $GITHUB_ENV

    - name: WORKSPACE env var with escaped backslashes Windows
      if: runner.os == 'Windows'
      shell: bash
      run: echo "WORKSPACE=${{github.workspace}}" | tr '\\' '/' >> $GITHUB_ENV

    - name: WORKSPACE env var not windows
      if: runner.os != 'Windows'
      shell: bash
      run: echo "WORKSPACE=$(pwd)" >> $GITHUB_ENV

    # VDB has some linking issue on macOS, disabling for now
    - name: Set SKBUILD_CMAKE_ARGS
      shell: bash
      run: >
        echo "SKBUILD_CMAKE_ARGS=-DF3D_DEPENDENCIES_DIR=${{ env.WORKSPACE }}/dependencies/install/bin;
        -DCMAKE_MODULE_PATH=${{ env.WORKSPACE }}/dependencies/install/lib/cmake/OpenVDB/;
        -DF3D_PLUGIN_BUILD_ALEMBIC=ON;
        -DF3D_PLUGIN_BUILD_ASSIMP=ON;
        -DF3D_PLUGIN_BUILD_DRACO=ON;
        -DF3D_PLUGIN_BUILD_OCCT=ON;
        -DF3D_PLUGIN_BUILD_USD=ON;
        -DF3D_PLUGIN_BUILD_VDB=${{ runner.os == 'macOS' && 'OFF' || 'ON' }};
        -DF3D_PLUGIN_OCCT_COLORING_SUPPORT=ON;
        -DF3D_MODULE_EXR=ON;
        -DF3D_MODULE_EXTERNAL_RENDERING=ON" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Build wheel
      shell: bash
      working-directory: ${{github.workspace}}/source
      run: python -m pip -v wheel .

    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        path: ./source/*.whl
        name: ${{runner.os}}-wheel

    - name: Install wheel
      shell: bash
      working-directory: ${{github.workspace}}/source
      run: python -m pip -v install *.whl

    - name: Run Xvfb ubuntu
      if: runner.os == 'Linux'
      shell: bash
      run: Xvfb $DISPLAY -screen 0 1280x1024x24 &

    - name: Install Mesa Windows
      if: runner.os == 'Windows'
      uses: ./source/.github/actions/mesa-install-bin
      with:
        path: ${{ env.Python_ROOT_DIR }}

    - name: Test wheel
      shell: bash
      working-directory: ${{github.workspace}}/source
      run: python -m pytest
