name: 'Install Mesa Windows'
description: 'Install Mesa Windows binaries to a specific directory'
inputs:
  path:
    description: 'path to install binaries to, supports wildcard'
    required: true
runs:
  using: "composite"
  steps:

    - name: Check required inputs
      shell: bash
      run: |
        [[ "${{ inputs.path }}" ]] || { echo "path input is empty" ; exit 1; }

    - name: Download and install Mesa windows
      shell: powershell
      run: |
        mkdir mesa
        cd mesa
        curl.exe -L --output mesa.7z --url https://github.com/pal1000/mesa-dist-win/releases/download/23.3.5/mesa3d-23.3.5-release-msvc.7z
        C:\'Program Files'\7-Zip\7z.exe x mesa.7z
        # A * is added next line to force Get-ChildItem to look for directory within the path
        Get-ChildItem -Directory ${{inputs.path}}* | ForEach-Object { Copy-Item -Path .\x64\opengl32.dll, .\x64\libglapi.dll, .\x64\libgallium_wgl.dll -Destination $_ }
        echo "GALLIUM_DRIVER=llvmpipe"| Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        cd ..
        rm .\mesa -r -force
