name: 'Android CI'
description: 'Android CI'
inputs:
  arch:
    description: 'Android arch to build'
    required: true

runs:
  using: "composite"
  steps:

    - name: Check required inputs
      shell: bash
      run: |
        [[ "${{inputs.arch}}" ]] || { echo "arch input is empty" ; exit 1; }

    - name: Setup Directories
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
         mkdir build
         mkdir install

    - name: Configure
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: >
        cmake ../source
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX:PATH=../install
        -DF3D_BINDINGS_JAVA=ON
        -DF3D_MODULE_EXR=ON
        -DF3D_MODULE_UI=OFF
        -DF3D_PLUGINS_STATIC_BUILD=ON
        -DF3D_PLUGIN_BUILD_ALEMBIC=ON
        -DF3D_PLUGIN_BUILD_ASSIMP=ON
        -DF3D_PLUGIN_BUILD_DRACO=ON
        -DF3D_PLUGIN_BUILD_EXODUS=OFF
        -DF3D_PLUGIN_BUILD_OCCT=ON
        -DF3D_STRICT_BUILD=ON

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --parallel 2 --target install

    - name: Upload native library
      uses: actions/upload-artifact@v4
      with:
        path: ./build/lib/libf3d-java.so
        name: f3d-android-native-${{inputs.arch}}

    - name: Upload Java package
      if: inputs.arch == 'arm64-v8a' # avoid duplication
      uses: actions/upload-artifact@v4
      with:
        path: ./build/java/f3d.jar
        name: f3d-android-jar
