name: 'Android CI'
description: 'Android CI'
inputs:
  arch:
    description: 'Android arch to build'
    required: true
  ndk_version:
    description: 'Version of the Android NDK to download'
    required: false
    default: 'r26b'
  api_level:
    description: 'Android API level'
    required: false
    default: '27'
  vtk_version:
    description: 'VTK version'
    required: false
    default: 'commit'

runs:
  using: "composite"
  steps:

    - name: Check required inputs
      shell: bash
      run: |
        [[ "${{inputs.arch}}" ]] || { echo "arch input is empty" ; exit 1; }

    - name: Dependencies Dir
      shell: bash
      working-directory: ${{github.workspace}}
      run: mkdir dependencies

    - name: Install NDK
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        apt-get install unzip
        wget https://dl.google.com/android/repository/android-ndk-${{inputs.ndk_version}}-linux.zip
        unzip -qq android-ndk-${{inputs.ndk_version}}-linux.zip
        mv android-ndk-${{inputs.ndk_version}} android-ndk

    - name: Install VTK dependency
      uses: ./source/.github/actions/vtk-android-install-dep
      with:
        arch: ${{inputs.arch}}
        api_level: ${{inputs.api_level}}
        vtk_version: ${{inputs.vtk_version}}
        vtk_sha_file: ./source/.github/actions/vtk_commit_sha

    - name: Setup Directories
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
         mkdir build
         mkdir install

    - name: Configure
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: >
        cmake ../source
        -DCMAKE_ANDROID_ARCH_ABI=${{inputs.arch}}
        -DCMAKE_ANDROID_NDK=$(pwd)/../android-ndk
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_FIND_ROOT_PATH=$(pwd)/../dependencies/vtk_build/CMakeExternals/Install/vtk-android/
        -DCMAKE_INSTALL_PREFIX:PATH=../install
        -DCMAKE_SYSTEM_NAME=Android
        -DCMAKE_SYSTEM_VERSION=${{inputs.api_level}}
        -DF3D_BINDINGS_JAVA=ON
        -DF3D_PLUGIN_BUILD_EXODUS=OFF
        -DF3D_STRICT_BUILD=ON

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --parallel 2 --target install

    - name: Upload native library
      uses: actions/upload-artifact@v4
      with:
        path: ./build/lib/libf3d-java.so
        name: f3d-android-native-${{inputs.arch}}

    - name: Upload Java package
      if: inputs.arch == 'arm64-v8a' # avoid duplication
      uses: actions/upload-artifact@v4
      with:
        path: ./build/java/f3d.jar
        name: f3d-android-jar
