name: "Install Assimp Dependency"
description: "Install Assimp Dependency using cache when possible"
inputs:
  versions_file:
    description: "File to recover versions from"
    required: true
  cpu:
    description: "CPU architecture to build for"
    required: false
    default: "x86_64"

runs:
  using: "composite"
  steps:
    - name: Check required inputs
      shell: bash
      run: |
        [[ "${{inputs.versions_file}}" ]] || { echo "versions_file is empty" ; exit 1; }

    - name: Extract assimp version
      id: assimp_ver
      uses: f3d-app/extract-version-action@main
      with:
        file: ${{inputs.versions_file}}
        name: assimp

    - name: Extract global cache index
      id: global_idx
      uses: f3d-app/extract-version-action@main
      with:
        file: ${{inputs.versions_file}}
        special_name: global_cache_index

    - name: Cache assimp
      id: cache-assimp
      uses: actions/cache/restore@v5
      with:
        path: dependencies/assimp_install
        key: assimp-${{steps.assimp_ver.outputs.extract}}-${{runner.os}}-${{inputs.cpu}}-${{steps.global_idx.outputs.extract}}-2

    - name: Checkout ASSIMP
      if: steps.cache-assimp.outputs.cache-hit != 'true'
      uses: actions/checkout@v6
      with:
        repository: assimp/assimp
        path: "./dependencies/assimp"
        ref: ${{steps.assimp_ver.outputs.extract}}

    - name: Setup ASSIMP
      if: steps.cache-assimp.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies
      shell: bash
      run: |
        mkdir assimp_build
        mkdir assimp_install

    - name: Configure ASSIMP
      if: steps.cache-assimp.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/assimp_build
      shell: bash
      run: >
        cmake ../assimp
        -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=OFF
        -DASSIMP_BUILD_ASSIMP_TOOLS=OFF
        -DASSIMP_BUILD_3MF_IMPORTER=ON
        -DASSIMP_BUILD_COLLADA_IMPORTER=ON
        -DASSIMP_BUILD_DXF_IMPORTER=ON
        -DASSIMP_BUILD_FBX_IMPORTER=ON
        -DASSIMP_BUILD_OFF_IMPORTER=ON
        -DASSIMP_BUILD_X_IMPORTER=ON
        -DASSIMP_BUILD_SAMPLES=OFF
        -DASSIMP_BUILD_TESTS=OFF
        -DASSIMP_NO_EXPORT=ON
        -DASSIMP_WARNINGS_AS_ERRORS=OFF
        -DBUILD_SHARED_LIBS=ON
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX:PATH=../assimp_install
        ${{ runner.os == 'macOS' && '-DCMAKE_OSX_DEPLOYMENT_TARGET=14.0' || null }}
        ${{ runner.os == 'Windows' && '-Ax64 -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL' || null }}

    - name: Build ASSIMP
      if: steps.cache-assimp.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/assimp_build
      shell: bash
      run: cmake --build . --parallel 2 --target install --config Release

    - name: Copy to install
      working-directory: ${{github.workspace}}/dependencies/assimp_install
      shell: bash
      run: cp -r ./* ../install/

    - name: Save cache
      if: steps.cache-assimp.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        key: ${{ steps.cache-assimp.outputs.cache-primary-key }}
        path: dependencies/assimp_install
