name: 'Install VTK Webassembly Dependency'
description: 'Install VTK Webassembly Dependency using cache when possible'
inputs:
  vtk_version:
    description: 'VTK version'
    required: false
    default: 'commit'
  vtk_sha_file:
    description: 'VTK SHA file'
    required: false
    default: ''

runs:
  using: "composite"
  steps:

    - name: Recover VTK Short SHA from file
      if: |
        steps.cache-vtk.outputs.cache-hit != 'true' &&
        inputs.vtk_version == 'commit'
      working-directory: ${{github.workspace}}
      shell: bash
      run: echo "VTK_SHA_OR_TAG=$(<${{ inputs.vtk_sha_file }})" >> $GITHUB_ENV

    - name: Copy VTK version to env var
      if: |
        steps.cache-vtk.outputs.cache-hit != 'true' &&
        inputs.vtk_version != 'commit'
      working-directory: ${{github.workspace}}
      shell: bash
      run: echo "VTK_SHA_OR_TAG=${{inputs.vtk_version}}" >> $GITHUB_ENV

    - name: Cache VTK
      id: cache-vtk
      uses: actions/cache@v4
      with:
        path: dependencies/vtk_install
        key: vtk-webassembly-${{env.VTK_SHA_OR_TAG}}-7

    - name: Setup VTK
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies
      shell: bash
      run: mkdir vtk_build

    - name: Checkout VTK
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: Kitware/VTK
        submodules: 'true'
        path: './dependencies/vtk'
        ref: ${{env.VTK_SHA_OR_TAG}}

    # Not that it's a bug in VTK and this step should be removed when fixed
    # See https://gitlab.kitware.com/vtk/vtk/-/merge_requests/11178
    - name: Patch js file install
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/vtk
      shell: bash
      run: patch -p1 < $GITHUB_ACTION_PATH/0001-fix-js-install.patch

    - name: Configure VTK
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/vtk_build
      shell: bash
      run: >
        cmake ../vtk
        -DBUILD_SHARED_LIBS=OFF
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX:PATH=../vtk_install
        -DCMAKE_PREFIX_PATH:PATH=$(pwd)/../install/
        -DVTK_BUILD_TESTING=OFF
        -DVTK_ENABLE_LOGGING=OFF
        -DVTK_ENABLE_REMOTE_MODULES=OFF
        -DVTK_ENABLE_WRAPPING=OFF
        -DVTK_LEGACY_REMOVE=ON
        -DVTK_GROUP_ENABLE_Imaging=DONT_WANT
        -DVTK_GROUP_ENABLE_MPI=DONT_WANT
        -DVTK_GROUP_ENABLE_Qt=DONT_WANT
        -DVTK_GROUP_ENABLE_Rendering=DONT_WANT
        -DVTK_GROUP_ENABLE_StandAlone=DONT_WANT
        -DVTK_GROUP_ENABLE_Views=DONT_WANT
        -DVTK_GROUP_ENABLE_Web=DONT_WANT
        -DVTK_MODULE_ENABLE_VTK_CommonCore=YES
        -DVTK_MODULE_ENABLE_VTK_CommonDataModel=YES
        -DVTK_MODULE_ENABLE_VTK_CommonExecutionModel=YES
        -DVTK_MODULE_ENABLE_VTK_CommonSystem=YES
        -DVTK_MODULE_ENABLE_VTK_FiltersGeneral=YES
        -DVTK_MODULE_ENABLE_VTK_FiltersGeometry=YES
        -DVTK_MODULE_ENABLE_VTK_IOCityGML=YES
        -DVTK_MODULE_ENABLE_VTK_IOImage=YES
        -DVTK_MODULE_ENABLE_VTK_IOImport=YES
        -DVTK_MODULE_ENABLE_VTK_IOPLY=YES
        -DVTK_MODULE_ENABLE_VTK_IOParallel=YES
        -DVTK_MODULE_ENABLE_VTK_IOXML=YES
        -DVTK_MODULE_ENABLE_VTK_ImagingCore=YES
        -DVTK_MODULE_ENABLE_VTK_ImagingHybrid=YES
        -DVTK_MODULE_ENABLE_VTK_InteractionStyle=YES
        -DVTK_MODULE_ENABLE_VTK_InteractionWidgets=YES
        -DVTK_MODULE_ENABLE_VTK_RenderingAnnotation=YES
        -DVTK_MODULE_ENABLE_VTK_RenderingCore=YES
        -DVTK_MODULE_ENABLE_VTK_RenderingOpenGL2=YES
        -DVTK_MODULE_ENABLE_VTK_RenderingVolumeOpenGL2=YES
        -DVTK_MODULE_ENABLE_VTK_TestingCore=YES
        -DVTK_SMP_IMPLEMENTATION_TYPE=Sequential
        -DVTK_VERSIONED_INSTALL=OFF

    - name: Build VTK
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/vtk_build
      shell: bash
      run: cmake --build . --parallel 2 --target install
