name: 'Install ISPC'
description: 'Install Android NDK using cache when possible'
inputs:
  os:
    description: 'OS to build on'
    required: false
    default: 'ubuntu-latest'

runs:
  using: "composite"
  steps:

    - name: Cache ISPC
      id: cache-ispc
      uses: actions/cache@v3
      with:
        path: dependencies/ispc
        key: ispc-v1.16.1-0-${{inputs.os}}

    - name: Download ISPC Linux
      if: |
        steps.cache-ispc.outputs.cache-hit != 'true' &&
        inputs.os == 'ubuntu-latest'
      working-directory: ${{github.workspace}}/dependencies/
      shell: bash
      run: |
        wget https://github.com/ispc/ispc/releases/download/v1.16.0/ispc-v1.16.0-linux.tar.gz
        tar -xzvf ispc-v1.16.0-linux.tar.gz
        mv ispc-v1.16.0-linux ispc

    - name: Download ISPC Windows
      if: |
        steps.cache-ispc.outputs.cache-hit != 'true' &&
        inputs.os == 'windows-latest'
      working-directory: ${{github.workspace}}/dependencies/
      shell: powershell
      run: |
        C:\msys64\usr\bin\wget.exe https://github.com/ispc/ispc/releases/download/v1.16.0/ispc-v1.16.0-windows.zip
        7z x ispc-v1.16.0-windows.zip
        mv ispc-v1.16.0-windows ispc

    - name: Download ISPC MacOS
      if: |
        steps.cache-ispc.outputs.cache-hit != 'true' &&
        inputs.os == 'macos-latest'
      working-directory: ${{github.workspace}}/dependencies/
      shell: bash
      run: |
        wget https://github.com/ispc/ispc/releases/download/v1.16.0/ispc-v1.16.0-macos.tar.gz
        tar -xzvf ispc-v1.16.0-macos.tar.gz
        mv ispc-v1.16.0-macos ispc
