name: 'Install PDAL Dependency'
description: 'Install PDAL Dependency using cache when possible'
inputs:
  cpu:
    description: 'CPU architecture to build for'
    required: false
    default: 'x86_64'
  version:
    description: 'Version of PDAL to build'
    required: true

runs:
  using: "composite"
  steps:

    - name: Check required inputs
      shell: bash
      run: |
        [[ "${{ inputs.version }}" ]] || { echo "version input is empty" ; exit 1; }

    - name: Cache PDAL
      id: cache-pdal
      uses: actions/cache/restore@v4
      with:
        path: dependencies/pdal_install
        key: pdal-${{inputs.version}}-${{runner.os}}-${{inputs.cpu}}-0

    # Dependents (not version): vtk
    - name: Checkout PDAL
      if: steps.cache-pdal.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: PDAL/PDAL
        path: './dependencies/pdal'
        ref: ${{inputs.version}}

    - name: Setup PDAL
      if: steps.cache-pdal.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies
      shell: bash
      run: |
        mkdir pdal_build
        mkdir pdal_install

    - name: Configure PDAL
      if: steps.cache-pdal.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/pdal_build
      shell: bash
      run: >
        cmake ../pdal
        -DBUILD_SHARED_LIBS=ON
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_CXX_STANDARD=17
        -DCMAKE_CXX_STANDARD_REQUIRED=ON
        -DCMAKE_CXX_EXTENSIONS=OFF
        -DCMAKE_INSTALL_LIBDIR:PATH=lib
        -DCMAKE_INSTALL_PREFIX=../pdal_install
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        -DCMAKE_PREFIX_PATH:PATH=$(pwd)/../install/
        -DWITH_TESTS=OFF
        -DWITH_COMPLETION=OFF
        -DWITH_LASZIP=ON
        -DWITH_ZSTD=ON
        -DWITH_LZMA=ON
        -DWITH_GDAL=ON
        ${{ runner.os == 'macOS' && '-DCMAKE_OSX_DEPLOYMENT_TARGET=12.0' || null }}
        ${{ runner.os == 'Windows' && '-Ax64 -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL' || null }}

    - name: Build PDAL
      if: steps.cache-pdal.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/pdal_build
      shell: bash
      run: cmake --build . --parallel 2 --target install --config Release

    - name: Copy to install
      working-directory: ${{github.workspace}}/dependencies/pdal_install
      shell: bash
      run: cp -r ./* ../install/

    - name: Save cache
      if: steps.cache-pdal.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        key: ${{ steps.cache-pdal.outputs.cache-primary-key }}
        path: dependencies/pdal_install
