name: 'Copy LFS data'
description: 'Copy LFS data using cache when possible'
inputs:
  lfs_sha:
    description: 'LFS sha to recover'
    required: true
  workflow_label:
    description: 'Whether this action produce/consume LFS data'
    default: 'producer'

runs:
  using: "composite"
  steps:

    - name: Check required inputs
      shell: bash
      run: |
        [[ "${{ inputs.lfs_sha }}" ]] || { echo "lfs_sha input is empty" ; exit 1; }
 
    - name: Cache LFS data
      id: cache-lfs
      uses: actions/cache@v3
      with:
        path: lfs_data
        key: lfs-data-${{inputs.lfs_sha}}-1

    - name: Checkout LFS data
      if: |
        steps.cache-lfs.outputs.cache-hit != 'true' &&
        inputs.workflow_label == 'producer'
      uses: actions/checkout@v3
      with:
        path: 'lfs_data'
        fetch-depth: 0
        lfs: true

    - name: Upload LFS artifact
      if: |
        steps.cache-lfs.outputs.cache-hit != 'true' &&
        inputs.workflow_label == 'producer'
      uses: actions/upload-artifact@master
      with:
        name: lfs-data
        path: lfs_data

    - name: Download LFS artifact
      id: download-artifact
      if: |
        steps.cache-lfs.outputs.cache-hit != 'true' &&
        inputs.workflow_label == 'consumer'
      uses: actions/download-artifact@master
      continue-on-error: true
      with:
        name: lfs-data
        path: lfs_data

    - name: Checkout LFS data
      if: |
        steps.cache-lfs.outputs.cache-hit != 'true' &&
        steps.download-artifact.outcome != 'success' &&
        inputs.workflow_label == 'consumer'
      uses: actions/checkout@v3
      with:
        path: 'lfs_data'
        fetch-depth: 0
        lfs: true

    - name: Setup LFS data
      working-directory: ${{github.workspace}}
      shell: bash
      run: cmake -P $GITHUB_ACTION_PATH/copy_lfs.cmake ./lfs_data ./source
