name: 'Copy LFS data'
description: 'Copy LFS data using cache when possible'
inputs:
  lfs_sha:
    description: 'LFS sha to recover'
    required: true
runs:
  using: "composite"
  steps:

    - name: Cache LFS data
      id: cache-lfs
      uses: actions/cache@v3
      with:
        path: lfs_data
        key: lfs-data-${{inputs.lfs_sha}}-1

    - name: Checkout LFS data
      if: steps.cache-lfs.outputs.cache-hit != true
      uses: actions/checkout@v3
      with:
        path: lfs_data
        fetch-depth: 0
        lfs: true

    - name: Setup LFS data
      working-directory: ${{github.workspace}}
      shell: bash
      run: cmake -P $GITHUB_ACTION_PATH/copy_lfs.cmake ./lfs_data ./source
