name: 'Copy LFS data'
description: 'Copy LFS data using cache when possible'
inputs:
  lfs_sha:
    description: 'LFS sha to recover'
    required: true
runs:
  using: "composite"
  steps:

    - name: Buggy step
      working-directory: ${{github.workspace}}
      shell: bash
      run: this script is not executed
