name: 'Install Draco Dependency'
description: 'Install Draco Dependency using cache when possible'
inputs:
  os:
    description: 'OS to build on'
    required: false
    default: 'ubuntu-latest'
runs:
  using: "composite"
  steps:

    - name: Cache Draco
      id: cache-draco
      uses: actions/cache@v3
      with:
        path: dependencies/draco_install
        key: draco-1.5.5-2-${{inputs.os}}

    - name: Checkout Draco
      if: steps.cache-draco.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: google/draco
        path: './dependencies/draco'
        ref: 1.5.5

    - name: Setup Draco
      if: steps.cache-draco.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies
      shell: bash
      run: |
        mkdir draco_build
        mkdir draco_install

    - name: Configure Draco
      if: steps.cache-draco.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/draco_build
      shell: bash
      run: >
        cmake ../draco
        -DBUILD_SHARED_LIBS=OFF
        -DDRACO_JS_GLUE=OFF
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        -DCMAKE_INSTALL_PREFIX=../draco_install
        ${{ inputs.os == 'macos-latest' && '-DCMAKE_OSX_DEPLOYMENT_TARGET=10.15' || null }}
        ${{ inputs.os == 'windows-latest' && '-Ax64 -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded' || null }}

    - name: Build Draco
      if: steps.cache-draco.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/draco_build
      shell: bash
      run: cmake --build . --parallel 2 --target install --config Release
