name: "Install GDAL Dependency"
description: "Install GDAL Dependency using cache when possible"
inputs:
  cpu:
    description: "CPU architecture to build for"
    required: false
    default: "x86_64"
  version:
    description: "Version of gdal to build"
    required: true
  proj_version:
    description: "Version of PROJ to build against"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check required inputs
      shell: bash
      run: |
        [[ "${{ inputs.version }}" ]] || { echo "version input is empty" ; exit 1; }
        [[ "${{ inputs.proj_version }}" ]] || { echo "proj_version input is empty" ; exit 1; }

    - name: Cache GDAL
      id: cache-gdal
      uses: actions/cache/restore@v4
      with:
        path: ${{github.workspace}}/dependencies/gdal_install
        key: gdal-${{inputs.version}}-${{inputs.proj_version}}-${{runner.os}}-${{inputs.cpu}}-cxx17-1

    - name: Checkout GDAL
      if: steps.cache-gdal.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: OSGeo/gdal
        path: "./dependencies/gdal"
        ref: ${{inputs.version}}

    - name: Setup GDAL
      if: steps.cache-gdal.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies
      shell: bash
      run: |
        mkdir gdal_build
        mkdir gdal_install

    - name: Configure GDAL
      if: steps.cache-gdal.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/gdal_build
      shell: bash
      run: >
        cmake ../gdal
        -DCMAKE_CXX_STANDARD=17
        -DCMAKE_CXX_STANDARD_REQUIRED=ON
        -DBUILD_SHARED_LIBS=ON
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX=../gdal_install
        -DCMAKE_PREFIX_PATH:PATH=$(pwd)/../install/
        ${{ runner.os == 'macOS' && '-DCMAKE_OSX_DEPLOYMENT_TARGET=12.0' || null }}
        ${{ runner.os == 'Windows' && '-Ax64 -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL' || null }}

    - name: Build GDAL
      if: steps.cache-gdal.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/gdal_build
      shell: bash
      run: cmake --build . --parallel 2 --target install --config Release

    - name: Copy to install
      working-directory: ${{github.workspace}}/dependencies/gdal_install
      shell: bash
      run: cp -r ./* ../install/

    - name: Save cache
      if: steps.cache-gdal.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        key: ${{ steps.cache-gdal.outputs.cache-primary-key }}
        path: dependencies/gdal_install
