name: 'Webassembly CI'
description: 'Webassembly CI'

runs:
  using: "composite"
  steps:

    - name: Dependencies Dir
      shell: bash
      working-directory: ${{github.workspace}}
      run: mkdir dependencies

    - name: Install VTK dependency
      uses: ./source/.github/actions/vtk-webassembly-install-dep

    - name: Setup Directories
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
         mkdir build
         mkdir install

    - name: Configure
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: >
        cmake ../source
        -DBUILD_SHARED_LIBS=OFF
        -DCMAKE_INSTALL_PREFIX:PATH=../install
        -DF3D_STRICT_BUILD=ON
        -DF3D_PLUGIN_BUILD_EXODUS=OFF
        -DCMAKE_BUILD_TYPE=Release
        -DVTK_DIR:PATH=$(pwd)/../dependencies/vtk_install/lib/cmake/vtk

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --parallel 2 --target install
