name: 'Install VTK Dependencies'
description: 'Install multiple VTK Dependencies'
inputs:
  cpu:
    description: 'CPU architecture to build for'
    required: false
    default: 'x86_64'
  source_dir:
    description: 'Source directory for actions'
    required: false
    default: './source'

runs:
  using: "composite"
  steps:

    - name: Install TBB
      uses: ${{inputs.source_dir}}/.github/actions/tbb-install-dep
      with:
        cpu: ${{inputs.cpu}}

    - name: Install Boost dependency
      uses: ${{inputs.source_dir}}/.github/actions/boost-install-dep

    - name: Install zlib
      uses: ${{inputs.source_dir}}/.github/actions/zlib-install-dep
      with:
        cpu: ${{inputs.cpu}}

    - name: Install blosc
      uses: ${{inputs.source_dir}}/.github/actions/blosc-install-dep
      with:
        cpu: ${{inputs.cpu}}

    - name: Install OpenVDB
      uses: ${{inputs.source_dir}}/.github/actions/openvdb-install-dep
      with:
        cpu: ${{inputs.cpu}}
