name: 'Install VTK Dependencies'
description: 'Install multiple VTK Dependencies'
inputs:
  cpu:
    description: 'CPU architecture to build for'
    required: false
    default: 'x86_64'
  source_dir:
    description: 'Source directory for actions'
    required: false
    default: './source'
  openvdb_version:
    description: 'Version of openvdb to build'
    required: false
  pdal_version:
    description: 'Version of PDAL to build'
    required: false

runs:
  using: "composite"
  steps:

    - name: Copy actions to a common directory TODO move to another step ?
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        mkdir .actions
        cp -r ${{inputs.source_dir}}/.github/actions/* .actions/

    - name: Install TBB
      uses: ./.actions/tbb-install-dep
      with:
        cpu: ${{inputs.cpu}}

    - name: Install zlib
      uses: ./.actions/zlib-install-dep
      with:
        cpu: ${{inputs.cpu}}

    - name: Install blosc
      uses: ./.actions/blosc-install-dep
      with:
        cpu: ${{inputs.cpu}}

    - name: Install GDAL
      uses: ./.actions/gdal-install-dep
      with:
        cpu: ${{inputs.cpu}}

    - name: Install OpenVDB
      if: inputs.openvdb_version != ''
      uses: ./.actions/openvdb-install-dep
      with:
        cpu: ${{inputs.cpu}}
        version: ${{inputs.openvdb_version}}

    - name: Install PDAL
      if: inputs.pdal_version != ''
      uses: ./.actions/pdal-install-dep
      with:
        cpu: ${{inputs.cpu}}
        version: ${{inputs.pdal_version}}
