name: "Install VTK Dependencies"
description: "Install multiple VTK Dependencies"
inputs:
  versions_file:
    description: "File to recover versions from"
    required: true
  optdeps_label:
    description: "Label to check for optional dependencies"
    required: false
    default: "optdeps"
  mindeps_label:
    description: "Label to check for minimal version dependencies"
    required: false
    default: "no-mindeps"
  cpu:
    description: "CPU architecture to build for"
    required: false
    default: "x86_64"
  source_dir:
    description: "Source directory for actions"
    required: false
    default: "./source"

runs:
  using: "composite"
  steps:
    - name: Check required inputs
      shell: bash
      run: |
        [[ "${{ inputs.versions_file }}" ]] || { echo "versions_file is empty" ; exit 1; }

    - name: Copy actions to a common directory, specific to external-build CI
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        mkdir .actions
        cp -r ${{inputs.source_dir}}/.github/actions/* .actions/

    - name: Install sqlite
      if: inputs.optdeps_label == 'optdeps'
      uses: ./.actions/sqlite-install-dep
      with:
        versions_file: ${{inputs.versions_file}}
        mindeps_label: ${{inputs.mindeps_label}}
        cpu: ${{inputs.cpu}}

    - name: Install proj
      if: inputs.optdeps_label == 'optdeps'
      uses: ./.actions/proj-install-dep
      with:
        versions_file: ${{inputs.versions_file}}
        mindeps_label: ${{inputs.mindeps_label}}
        cpu: ${{inputs.cpu}}

    - name: Install TBB
      uses: ./.actions/tbb-install-dep
      with:
        versions_file: ${{inputs.versions_file}}
        mindeps_label: ${{inputs.mindeps_label}}
        cpu: ${{inputs.cpu}}

    - name: Install zlib
      uses: ./.actions/zlib-install-dep
      with:
        versions_file: ${{inputs.versions_file}}
        mindeps_label: ${{inputs.mindeps_label}}
        cpu: ${{inputs.cpu}}

    - name: Install curl
      if: inputs.optdeps_label == 'optdeps'
      uses: ./.actions/curl-install-dep
      with:
        versions_file: ${{inputs.versions_file}}
        mindeps_label: ${{inputs.mindeps_label}}
        cpu: ${{inputs.cpu}}

    - name: Install blosc
      uses: ./.actions/blosc-install-dep
      with:
        versions_file: ${{inputs.versions_file}}
        mindeps_label: ${{inputs.mindeps_label}}
        cpu: ${{inputs.cpu}}

    - name: Install tiff
      if: inputs.optdeps_label == 'optdeps'
      uses: ./.actions/tiff-install-dep
      with:
        versions_file: ${{inputs.versions_file}}
        mindeps_label: ${{inputs.mindeps_label}}
        cpu: ${{inputs.cpu}}

    - name: Install geotiff
      if: inputs.optdeps_label == 'optdeps'
      uses: ./.actions/geotiff-install-dep
      with:
        versions_file: ${{inputs.versions_file}}
        mindeps_label: ${{inputs.mindeps_label}}
        cpu: ${{inputs.cpu}}

    - name: Install gdal
      if: inputs.optdeps_label == 'optdeps'
      uses: ./.actions/gdal-install-dep
      with:
        versions_file: ${{inputs.versions_file}}
        mindeps_label: ${{inputs.mindeps_label}}
        cpu: ${{inputs.cpu}}

    - name: Install pdal
      if: inputs.optdeps_label == 'optdeps'
      uses: ./.actions/pdal-install-dep
      with:
        versions_file: ${{inputs.versions_file}}
        mindeps_label: ${{inputs.mindeps_label}}
        cpu: ${{inputs.cpu}}

    - name: Install OpenVDB
      if: inputs.optdeps_label == 'optdeps'
      uses: ./.actions/openvdb-install-dep
      with:
        versions_file: ${{inputs.versions_file}}
        mindeps_label: ${{inputs.mindeps_label}}
        cpu: ${{inputs.cpu}}
