## Tests that needs occt plugin
## This file is only added if occt is enabled
f3d_test(NAME TestSTEP DATA f3d.stp ARGS --load-plugins=occt --up=+Z)
f3d_test(NAME TestIGES DATA f3d.igs ARGS --load-plugins=occt --up=+Z)
f3d_test(NAME TestBREP DATA f3d.brep ARGS --load-plugins=occt --up=+Z)
f3d_test(NAME TestBinaryBREP DATA f3d.bin.brep ARGS --load-plugins=occt --up=+Z)
f3d_test(NAME TestSTEPDefines DATA cheese.stp ARGS --load-plugins=occt -DSTEP.linear_deflection=0.5 -DSTEP.angular_deflection=0.9 -DSTEP.relative_deflection=1)
f3d_test(NAME TestIGESDefines DATA cheese.igs ARGS --load-plugins=occt -DIGES.read_wire=0 --line-width=5 --up=+Z)
f3d_test(NAME TestBREPDefines DATA cheese.brep ARGS --load-plugins=occt -DBREP.linear_deflection=100 --up=+Z)

if(VTK_VERSION VERSION_GREATER_EQUAL 9.3.20240707)
  f3d_test(NAME TestInvalidSTEP DATA invalid_truncated.stp ARGS --verbose --load-plugins=occt REGEXP "failed to load scene" NO_BASELINE)
  f3d_test(NAME TestInvalidBREP DATA invalid_truncated.brep ARGS --verbose --load-plugins=occt REGEXP "failed to load scene" NO_BASELINE)
endif()

if(VTK_VERSION VERSION_GREATER_EQUAL 9.6.20260128)
  f3d_test(NAME TestPipedSTEP DATA f3d.stp ARGS --load-plugins=occt --up=+Z PIPED)
  f3d_test(NAME TestPipedBREP DATA f3d.brep ARGS --load-plugins=occt --up=+Z PIPED)
  f3d_test(NAME TestPipedBinaryBREP DATA f3d.bin.brep ARGS --load-plugins=occt --up=+Z PIPED)
elseif(VTK_VERSION VERSION_GREATER_EQUAL 9.5.20251223)
  f3d_test(NAME TestPipedSTEP DATA f3d.stp ARGS --load-plugins=occt --up=+Z --force-reader=STEP PIPED)
  f3d_test(NAME TestPipedBREP DATA f3d.brep ARGS --load-plugins=occt --up=+Z --force-reader=BREP PIPED)
  f3d_test(NAME TestPipedBinaryBREP DATA f3d.bin.brep ARGS --load-plugins=occt --up=+Z --force-reader=BREP PIPED)
endif()

if(F3D_PLUGIN_OCCT_COLORING_SUPPORT)
  f3d_test(NAME TestXBF DATA f3d.xbf ARGS --load-plugins=occt --up=+Z)
  f3d_test(NAME TestXBFDefines DATA cheese.xbf ARGS --load-plugins=occt -DXBF.angular_deflection=1 -DXBF.relative_deflection=1 --up=+Z)
  f3d_test(NAME TestXCAFColors DATA xcaf-colors.stp ARGS --load-plugins=occt -csy --up=+Z --line-width=3 --camera-direction=-1,-1,-1)
  f3d_test(NAME TestXCAFColorsXBF DATA xcaf-colors.xbf ARGS --load-plugins=occt -csy --up=+Z --line-width=3 --camera-direction=-1,-1,-1)
  if(VTK_VERSION VERSION_GREATER_EQUAL 9.3.20240707)
    f3d_test(NAME TestInvalidXBF DATA invalid_truncated.xbf ARGS --verbose --load-plugins=occt REGEXP "failed to load scene" NO_BASELINE)
  endif()
  if(VTK_VERSION VERSION_GREATER_EQUAL 9.6.20260128)
    f3d_test(NAME TestPipedXBF DATA f3d.xbf ARGS --load-plugins=occt --up=+Z PIPED)
  elseif(VTK_VERSION VERSION_GREATER_EQUAL 9.5.20251223)
    f3d_test(NAME TestPipedXBF DATA f3d.xbf ARGS --load-plugins=occt --up=+Z --force-reader=XBF PIPED)
  endif()

  if (NOT F3D_MACOS_BUNDLE)
    file(COPY "${F3D_SOURCE_DIR}/plugins/occt/configs/config.d/" DESTINATION "${CMAKE_BINARY_DIR}/share/f3d/configs/config_build.d")
    # Needs https://gitlab.kitware.com/vtk/vtk/-/merge_requests/12489
    if(VTK_VERSION VERSION_GREATER_EQUAL 9.5.20251001)
      f3d_test(NAME TestDefaultConfigFileOCCT DATA f3d.stp CONFIG config_build LONG_TIMEOUT TONE_MAPPING UI)
    endif()

    file(COPY "${F3D_SOURCE_DIR}/plugins/occt/configs/thumbnail.d/" DESTINATION "${CMAKE_BINARY_DIR}/share/f3d/configs/thumbnail_build.d")
    f3d_test(NAME TestThumbnailConfigFileOCCT DATA f3d.stp CONFIG thumbnail_build LONG_TIMEOUT TONE_MAPPING)
  endif()
endif()
