## Tests file formats from native plugin
f3d_test(NAME TestPLY DATA suzanne.ply)
f3d_test(NAME TestOBJ DATA world.obj)
f3d_test(NAME TestSTL DATA suzanne.stl)
f3d_test(NAME TestVTICell DATA waveletMaterial.vti ARGS -s --coloring-array=Material -c --roughness=1)
f3d_test(NAME TestVTU DATA dragon.vtu)
f3d_test(NAME TestVTP DATA cow.vtp)
f3d_test(NAME TestVTR DATA RectGrid2.vtr ARGS --scalar-coloring --roughness=1)
f3d_test(NAME TestVTS DATA bluntfin.vts)
f3d_test(NAME TestVTM DATA mb.vtm)
f3d_test(NAME TestVTK DATA cow.vtk)
f3d_test(NAME TestNRRD DATA beach.nrrd ARGS -s)
f3d_test(NAME TestVRMLImporter DATA bot2.wrl)
f3d_test(NAME TestCityGML DATA Part-4-Buildings-V4-one.gml)
f3d_test(NAME TestPTS DATA samplePTS.pts)
f3d_test(NAME TestDicom DATA IM-0001-1983.dcm ARGS --scalar-coloring --roughness=1)
f3d_test(NAME TestMHD DATA HeadMRVolume.mhd ARGS --scalar-coloring --roughness=1)
f3d_test(NAME TestTIFF DATA f3d.tif ARGS -sy --up=-Y)
f3d_test(NAME TestPNG DATA world.png ARGS --scalar-coloring --up=+Y --coloring-component=-2 --camera-direction=0,0,-1 --camera-orthographic)
f3d_test(NAME TestJPG DATA world.jpg ARGS --scalar-coloring --up=+Y --coloring-component=-2 --camera-direction=0,0,-1 --camera-orthographic)
f3d_test(NAME TestBMP DATA albedo.bmp ARGS --scalar-coloring --up=+Y --coloring-component=-2 --camera-direction=0,0,-1 --camera-orthographic)
f3d_test(NAME TestTGA DATA world.tga ARGS --scalar-coloring --up=+Y --coloring-component=-2 --camera-direction=0,0,-1 --camera-orthographic)
if(NOT APPLE) # HDR banding renders differently on macOS, can be removed once banding issue is fixed
  f3d_test(NAME TestHDR DATA palermo_park_1k.hdr ARGS --scalar-coloring --up=+Y --coloring-component=-2 --camera-direction=0,0,-1 --camera-orthographic)
endif()
f3d_test(NAME Test3DSImporter DATA iflamigm.3ds ARGS --up=+Z)
f3d_test(NAME TestGLTFImporter DATA f3d.glb)
f3d_test(NAME TestGLTFImporterWithAnimation DATA BoxAnimated.gltf ARGS --animation-time=2 --animation-progress)
f3d_test(NAME TestGLTFSkin DATA SimpleSkin.gltf)
f3d_test(NAME TestGLTFImporterUnlit DATA UnlitTest.glb)
f3d_test(NAME TestGLTFMorph DATA SimpleMorph.gltf)
f3d_test(NAME TestGLTFURI DATA Lantern/Lantern.gltf)
f3d_test(NAME TestQuakeMDL DATA zombie.mdl)
f3d_test(NAME TestQuakeMDLAnimationSimpleFrame DATA zombie.mdl ARGS --animation-time=0.5)
f3d_test(NAME TestQuakeMDLAnimationBetween DATA zombie.mdl ARGS --animation-time=1.42)
f3d_test(NAME TestQuakeMDLAnimationMulti DATA soldier_animations.mdl ARGS --animation-indices=2 --animation-time=0.5)
f3d_test(NAME TestQuakeMDLAnimationGroupFrame DATA flame_mixed.mdl ARGS --animation-indices=1 --animation-time=0.5)
f3d_test(NAME TestQuakeMDLAnimationLastFrame DATA flame_mixed.mdl ARGS --camera-position=90,0,0 --animation-time=0.65)
f3d_test(NAME TestQuakeMDLDisableAnimation DATA zombie.mdl soldier_animations.mdl ARGS --multi-file-mode=all --animation-time=0.5)
f3d_test(NAME TestQuakeMDLSkinIndex DATA armor.mdl ARGS -DQuakeMDL.skin_index=2)
f3d_test(NAME TestQuakeMDLSkinIndexNegative DATA armor.mdl ARGS -DQuakeMDL.skin_index=-1)
f3d_test(NAME TestQuakeMDLSkinIndexNonInteger DATA armor.mdl ARGS -DQuakeMDL.skin_index=1.5)
f3d_test(NAME TestQuakeMDLSkinIndexOutOfBounds DATA armor.mdl ARGS -DQuakeMDL.skin_index=4)
f3d_test(NAME TestQuakeMDLSkinIndexOverflow DATA armor.mdl ARGS -DQuakeMDL.skin_index=9223372036854775808)
f3d_test(NAME TestQuakeMDLGroupSkin DATA groupskin.mdl ARGS --animation-indices=1 --animation-time=0.3)
f3d_test(NAME TestVerboseQuakeMDLAnimationNoNamingScheme ARGS --verbose DATA v_rock2.mdl REGEXP "0: flame" NO_BASELINE)
f3d_test(NAME TestVerboseQuakeMDLGroupSkin ARGS --verbose DATA groupskin.mdl REGEXP "0: group_skin" NO_BASELINE)
f3d_test(NAME TestVerboseQuakeMDLInvalid ARGS --verbose DATA w_medkit_hl.mdl REGEXP "Unsupported MDL version" NO_BASELINE)

if(VTK_VERSION VERSION_GREATER_EQUAL 9.3.20231102)
  f3d_test(NAME TestSPLAT DATA small.splat ARGS -osy --up=-Y --point-sprites-absolute-size --point-sprites-size=1)
  f3d_test(NAME TestSPLATSortCPU DATA small.splat ARGS -osy --point-sprites=gaussian --up=-Y --point-sprites-absolute-size --point-sprites-size=1 --blending=sort_cpu --camera-position=2,0,0)
  f3d_test(NAME TestSPZ DATA hornedlizard_small_d0.spz ARGS -sy --point-sprites-absolute-size --point-sprites-size=1)

  set(_splat_args -sy --up=-Y --point-sprites-absolute-size --point-sprites-size=1 --camera-position=-2.00335,1.09654,-0.459485 --camera-focal-point=-0.796712,2.22795,0.705742)
  f3d_test(NAME TestSPLATSphere DATA small.splat ARGS ${_splat_args} --point-sprites=sphere)
  f3d_test(NAME TestSPLATCircle DATA small.splat ARGS ${_splat_args} --point-sprites=circle)
  f3d_test(NAME TestSPLATStdDev DATA small.splat ARGS ${_splat_args} --point-sprites=stddev)
  f3d_test(NAME TestSPLATBound DATA small.splat ARGS ${_splat_args} --point-sprites=bound)
  f3d_test(NAME TestSPLATCross DATA small.splat ARGS ${_splat_args} --point-sprites=cross)
endif()

if(VTK_VERSION VERSION_GREATER_EQUAL 9.3.20240707)
  f3d_test(NAME TestQuakeMDLActorCollection DATA zombie.mdl ARGS --scalar-coloring)
endif()

# TGA support for OBJ added in https://gitlab.kitware.com/vtk/vtk/-/merge_requests/11922
if(VTK_VERSION VERSION_GREATER_EQUAL 9.4.20250220)
  f3d_test(NAME TestOBJWithTGATexture DATA world_tga.obj)
endif()

if(VTK_VERSION VERSION_GREATER_EQUAL 9.4.20250501)
  f3d_test(NAME TestPipedPLY DATA suzanne.ply ARGS --force-reader=PLYReader PIPED)
  f3d_test(NAME TestPipedQuakeMDL DATA zombie.mdl ARGS --force-reader=QuakeMDL PIPED)
  f3d_test(NAME TestPipedSPLAT DATA small.splat ARGS -osy --up=-Y --point-sprites-absolute-size --point-sprites-size=1 --force-reader=Splat PIPED)
  f3d_test(NAME TestPipedSPZ DATA hornedlizard_small_d0.spz ARGS -sy --point-sprites-absolute-size --point-sprites-size=1 --force-reader=SPZ PIPED)
  f3d_test(NAME TestPipedInvalid DATA suzanne.ply ARGS --force-reader=QuakeMDL PIPED REGEXP "Input stream could not be loaded" NO_BASELINE)
endif()

if(VTK_VERSION VERSION_GREATER_EQUAL 9.5.20250923)
  f3d_test(NAME TestPipedGLTFImporter DATA f3d.glb ARGS --force-reader=GLB PIPED)
  f3d_test(NAME TestPipedGLTFSkin DATA SimpleSkin.gltf ARGS --force-reader=GLTF PIPED)
endif()  

if(VTK_VERSION VERSION_GREATER_EQUAL 9.5.20250925)
  f3d_test(NAME TestPiped3DSImporter DATA iflamigm.3ds ARGS --up=+Z --force-reader=3DS PIPED)
endif()

if(VTK_VERSION VERSION_GREATER_EQUAL 9.5.20251104)
  f3d_test(NAME TestPipedSTL DATA suzanne.stl ARGS --force-reader=STL PIPED)
  if(NOT F3D_MACOS_BUNDLE)
    f3d_test(NAME TestDefaultConfigFilePipedSTL DATA suzanne.stl ARGS --force-reader=STL CONFIG config_build LONG_TIMEOUT UI PIPED)
  endif()
endif()

if(VTK_VERSION VERSION_GREATER_EQUAL 9.5.20251109)
  f3d_test(NAME TestPipedPTS DATA samplePTS.pts ARGS --force-reader=PTS PIPED)
endif()  

if(VTK_VERSION VERSION_GREATER_EQUAL 9.5.20251208)
  f3d_test(NAME TestPipedCityGML DATA Part-4-Buildings-V4-one.gml ARGS --force-reader=CityGML PIPED)
endif()

if(VTK_VERSION VERSION_GREATER_EQUAL 9.5.20251210)
  f3d_test(NAME TestPipedDicom DATA IM-0001-1983.dcm ARGS --scalar-coloring --roughness=1 --force-reader=DICOM PIPED)
endif()

if(VTK_VERSION VERSION_GREATER_EQUAL 9.6.20260103)
  f3d_test(NAME TestPipedOBJ DATA world.obj ARGS --force-reader=OBJ PIPED) # MTL and Textures not loaded
  f3d_test(NAME TestPipedVTK DATA cow.vtk ARGS --force-reader=VTKLegacy PIPED)
endif()

if(VTK_VERSION VERSION_GREATER_EQUAL 9.6.20260106)
  f3d_test(NAME TestPipedVTR DATA RectGrid2.vtr ARGS --scalar-coloring --roughness=1 --force-reader=VTKXMLVTR PIPED)
  f3d_test(NAME TestPipedVTU DATA dragon.vtu ARGS --force-reader=VTKXMLVTU PIPED)
  f3d_test(NAME TestPipedVTP DATA cow.vtp ARGS --force-reader=VTKXMLVTP PIPED)
  f3d_test(NAME TestPipedVTS DATA bluntfin.vts ARGS --force-reader=VTKXMLVTS PIPED)
  f3d_test(NAME TestPipedVTICell DATA waveletMaterial.vti ARGS -s --coloring-array=Material -c --roughness=1 --force-reader=VTKXMLVTI PIPED)
  f3d_test(NAME TestPipedPNG DATA world.png ARGS --scalar-coloring --up=+Y --coloring-component=-2 --camera-direction=0,0,-1 --camera-orthographic --force-reader=PNG PIPED)
  f3d_test(NAME TestPipedJPG DATA world.jpg ARGS --scalar-coloring --up=+Y --coloring-component=-2 --camera-direction=0,0,-1 --camera-orthographic --force-reader=JPEG PIPED)
  f3d_test(NAME TestPipedBMP DATA albedo.bmp ARGS --scalar-coloring --up=+Y --coloring-component=-2 --camera-direction=0,0,-1 --camera-orthographic --force-reader=BMP PIPED)
  f3d_test(NAME TestPipedTGA DATA world.tga ARGS --scalar-coloring --up=+Y --coloring-component=-2 --camera-direction=0,0,-1 --camera-orthographic --force-reader=TGA PIPED)
  if(NOT APPLE) # HDR banding renders differently on macOS, can be removed once banding issue is fixed
    f3d_test(NAME TestPipedHDR DATA palermo_park_1k.hdr ARGS --scalar-coloring --up=+Y --coloring-component=-2 --camera-direction=0,0,-1 --camera-orthographic --force-reader=HDR PIPED)
  endif()
endif()

if(NOT F3D_MACOS_BUNDLE)
  # On linux, we can easily test the config file search from the binary code by positioning a config file in the binary dir
  configure_file("${F3D_SOURCE_DIR}/testing/configs/complex.json" "${CMAKE_BINARY_DIR}/share/f3d/configs/complex_build.json" COPYONLY)
  file(COPY "${F3D_SOURCE_DIR}/resources/configs/config.d/" "${F3D_SOURCE_DIR}/plugins/native/configs/config.d/" DESTINATION "${CMAKE_BINARY_DIR}/share/f3d/configs/config_build.d")
  # Needs https://gitlab.kitware.com/vtk/vtk/-/merge_requests/12489
  if(VTK_VERSION VERSION_GREATER_EQUAL 9.5.20251001)
    f3d_test(NAME TestConfigFileBuild DATA dragon.vtu CONFIG complex_build.json UI)
    f3d_test(NAME TestConfigStemBuild DATA dragon.vtu CONFIG complex_build UI)
    f3d_test(NAME TestConfigFileUpperCase DATA suzanne_upper.STL CONFIG complex_build UI)
    f3d_test(NAME TestConfigFileMultiFileSTL DATA mb/recursive/mb_1_0.vtp suzanne.stl ARGS --multi-file-mode=all CONFIG complex_build UI)
    f3d_test(NAME TestConfigFileMultiFileVTP DATA mb/recursive/mb_1_0.vtp suzanne.stl mb/recursive/mb_2_0.vtp ARGS --multi-file-mode=all CONFIG complex_build UI)

    f3d_test(NAME TestDefaultConfigFileVTU DATA dragon.vtu CONFIG config_build LONG_TIMEOUT TONE_MAPPING UI)
    f3d_test(NAME TestDefaultConfigFileVTI DATA vase_4comp.vti CONFIG config_build LONG_TIMEOUT TONE_MAPPING UI)
    f3d_test(NAME TestDefaultConfigFileSTL DATA suzanne.stl CONFIG config_build LONG_TIMEOUT TONE_MAPPING UI)
    f3d_test(NAME TestDefaultConfigFileTIFF DATA f3d.tif CONFIG config_build LONG_TIMEOUT TONE_MAPPING UI) # Note: This tests config file order as camera_direction is set in different files
    f3d_test(NAME TestDefaultConfigFilePNG DATA world.png CONFIG config_build LONG_TIMEOUT TONE_MAPPING UI)
    f3d_test(NAME TestDefaultConfigFileJPG DATA world.jpg CONFIG config_build LONG_TIMEOUT TONE_MAPPING UI)
    f3d_test(NAME TestDefaultConfigFileBMP DATA albedo.bmp CONFIG config_build LONG_TIMEOUT TONE_MAPPING UI)
    f3d_test(NAME TestDefaultConfigFileTGA DATA world.tga CONFIG config_build LONG_TIMEOUT TONE_MAPPING UI)
    f3d_test(NAME TestDefaultConfigFileHDR DATA palermo_park_1k.hdr CONFIG config_build LONG_TIMEOUT TONE_MAPPING UI)
    f3d_test(NAME TestDefaultConfigFilePLY DATA suzanneRGBA.ply CONFIG config_build LONG_TIMEOUT TONE_MAPPING UI)
    f3d_test(NAME TestDefaultConfigFileQuakeMDL DATA zombie.mdl CONFIG config_build LONG_TIMEOUT TONE_MAPPING UI)
    f3d_test(NAME TestDefaultConfigFileAndCommand DATA suzanne.stl ARGS --up=-Y --camera-direction=-1,0.5,-1 CONFIG config_build LONG_TIMEOUT TONE_MAPPING UI)
    f3d_test(NAME TestDefaultConfigTranslucent DATA red_translucent_monkey.gltf CONFIG config_build LONG_TIMEOUT TONE_MAPPING UI)
    f3d_test(NAME TestDefaultConfigRemoveEmptyFileGroups DATA invalid.vtp cow.vtp CONFIG config_build LONG_TIMEOUT TONE_MAPPING UI)
  endif()

  file(COPY "${F3D_SOURCE_DIR}/resources/configs/thumbnail.d/" "${F3D_SOURCE_DIR}/plugins/native/configs/thumbnail.d/" DESTINATION "${CMAKE_BINARY_DIR}/share/f3d/configs/thumbnail_build.d")
  f3d_test(NAME TestThumbnailConfigFileVTU DATA dragon.vtu CONFIG thumbnail_build LONG_TIMEOUT TONE_MAPPING)
  f3d_test(NAME TestThumbnailConfigFileVTI DATA vase_4comp.vti CONFIG thumbnail_build LONG_TIMEOUT TONE_MAPPING)
  f3d_test(NAME TestThumbnailConfigFileSTL DATA suzanne.stl CONFIG thumbnail_build LONG_TIMEOUT TONE_MAPPING)
  f3d_test(NAME TestThumbnailConfigFilePLY DATA suzanneRGBA.ply CONFIG thumbnail_build LONG_TIMEOUT TONE_MAPPING)
  f3d_test(NAME TestThumbnailConfigFileTGA DATA world.tga CONFIG thumbnail_build LONG_TIMEOUT TONE_MAPPING)
  f3d_test(NAME TestThumbnailConfigFileHDR DATA palermo_park_1k.hdr CONFIG thumbnail_build LONG_TIMEOUT TONE_MAPPING)
  f3d_test(NAME TestThumbnailConfigFileQuakeMDL DATA zombie.mdl CONFIG thumbnail_build LONG_TIMEOUT TONE_MAPPING)
endif()
