## Tests that needs pdal plugin
## This file is only added if pdal is enabled
f3d_test(NAME TestLAS DATA warsaw_small.las PLUGIN pdal ARGS --scalar-coloring --coloring-array=Color --coloring-component=-1)
f3d_test(NAME TestLAZ DATA simple.laz PLUGIN pdal ARGS --scalar-coloring --coloring-array=Color --coloring-component=-1)
f3d_test(NAME TestBPF DATA simple-extra.bpf PLUGIN pdal ARGS --scalar-coloring --coloring-array=Color --coloring-component=-1)
f3d_test(NAME TestTerraScanBin DATA 20020715-time-color.bin PLUGIN pdal ARGS --scalar-coloring --coloring-array=Color --coloring-component=-1)
f3d_test(NAME TestPCD DATA autzen-utm.pcd PLUGIN pdal ARGS --scalar-coloring --coloring-array=Color --coloring-component=-1)
f3d_test(NAME TestPTX DATA 1.2-with-color.ptx PLUGIN pdal ARGS --scalar-coloring --coloring-array=Color --coloring-component=-1)
f3d_test(NAME TestSBET DATA autzen_trim.sbet PLUGIN pdal ARGS --scalar-coloring --coloring-array=GpsTime)

# Default camera position goes wrong because of https://github.com/f3d-app/f3d/issues/2921
# and the only sample file found was the one from pdal
f3d_test(NAME TestCSD DATA sample.csd PLUGIN pdal ARGS --scalar-coloring --camera-direction=-1,-1,-1)
f3d_test(NAME TestQI DATA 10-word.qi PLUGIN pdal ARGS --scalar-coloring --camera-direction=-1,-1,-1)
f3d_test(NAME TestSLPK DATA SMALL_AUTZEN_LAS_All.slpk PLUGIN pdal ARGS --camera-direction=-1,-1,-1)

f3d_test(NAME TestInvalidPDAL DATA f3d.vtp PLUGIN pdal ARGS --force-reader=LAS  REGEXP "failed to load scene" NO_BASELINE)

if(NOT F3D_MACOS_BUNDLE)
  file(COPY "${F3D_SOURCE_DIR}/plugins/pdal/configs/config.d/" DESTINATION "${CMAKE_BINARY_DIR}/share/f3d/configs/config_build.d")
  if(VTK_VERSION VERSION_GREATER_EQUAL 9.5.20251001)
    f3d_test(NAME TestDefaultConfigFileLAS DATA warsaw_small.las CONFIG config_build LONG_TIMEOUT LABELS "pdal;plugin" THRESHOLD 0.08)
    f3d_test(NAME TestDefaultConfigFileLAZ DATA simple.laz CONFIG config_build LONG_TIMEOUT LABELS "pdal;plugin")
    f3d_test(NAME TestDefaultConfigFileBPF DATA simple-extra.bpf CONFIG config_build LONG_TIMEOUT LABELS "pdal;plugin")
    f3d_test(NAME TestDefaultConfigFileTerraScanBin DATA 20020715-time-color.bin CONFIG config_build LONG_TIMEOUT LABELS "pdal;plugin" THRESHOLD 0.06)
    f3d_test(NAME TestDefaultConfigFilePCD DATA autzen-utm.pcd CONFIG config_build LONG_TIMEOUT LABELS "pdal;plugin" THRESHOLD 0.05)
    f3d_test(NAME TestDefaultConfigFilePTX DATA 1.2-with-color.ptx CONFIG config_build LONG_TIMEOUT LABELS "pdal;plugin")
    f3d_test(NAME TestDefaultConfigFileSBET DATA autzen_trim.sbet ARGS --coloring-array=GpsTime CONFIG config_build LONG_TIMEOUT LABELS "pdal;plugin")
    f3d_test(NAME TestDefaultConfigFileCSD DATA sample.csd CONFIG config_build LONG_TIMEOUT LABELS "pdal;plugin")
    f3d_test(NAME TestDefaultConfigFileQI DATA 10-word.qi CONFIG config_build LONG_TIMEOUT LABELS "pdal;plugin")
    f3d_test(NAME TestDefaultConfigFileSLPK DATA SMALL_AUTZEN_LAS_All.slpk CONFIG config_build LONG_TIMEOUT LABELS "pdal;plugin")
  endif()
  file(COPY "${F3D_SOURCE_DIR}/plugins/pdal/configs/thumbnail.d/" DESTINATION "${CMAKE_BINARY_DIR}/share/f3d/configs/thumbnail_build.d")
  f3d_test(NAME TestThumbnailConfigFileLAS DATA warsaw_small.las CONFIG thumbnail_build LONG_TIMEOUT LABELS "pdal;plugin")
  f3d_test(NAME TestThumbnailConfigFileLAZ DATA simple.laz CONFIG thumbnail_build LONG_TIMEOUT LABELS "pdal;plugin")
  f3d_test(NAME TestThumbnailConfigFileBPF DATA simple-extra.bpf CONFIG thumbnail_build LONG_TIMEOUT LABELS "pdal;plugin")
  f3d_test(NAME TestThumbnailConfigFileTerraScanBin DATA 20020715-time-color.bin CONFIG thumbnail_build LONG_TIMEOUT LABELS "pdal;plugin")
  f3d_test(NAME TestThumbnailConfigFilePCD DATA autzen-utm.pcd CONFIG thumbnail_build LONG_TIMEOUT LABELS "pdal;plugin")
  f3d_test(NAME TestThumbnailConfigFilePTX DATA 1.2-with-color.ptx CONFIG thumbnail_build LONG_TIMEOUT LABELS "pdal;plugin")
  f3d_test(NAME TestThumbnailConfigFileSBET DATA autzen_trim.sbet ARGS --coloring-array=GpsTime CONFIG thumbnail_build LONG_TIMEOUT LABELS "pdal;plugin")
  f3d_test(NAME TestThumbnailConfigFileCSD DATA sample.csd CONFIG thumbnail_build LONG_TIMEOUT LABELS "pdal;plugin")
  f3d_test(NAME TestThumbnailConfigFileQI DATA 10-word.qi CONFIG thumbnail_build LONG_TIMEOUT LABELS "pdal;plugin")
  f3d_test(NAME TestThumbnailConfigFileSLPK DATA SMALL_AUTZEN_LAS_All.slpk CONFIG thumbnail_build LONG_TIMEOUT LABELS "pdal;plugin")
endif()
