name: "Install Alembic Dependency"
description: "Install Alembic Dependency using cache when possible"
inputs:
  cpu:
    description: "CPU architecture to build for"
    required: false
    default: "x86_64"
  version:
    description: "Version of alembic to build"
    required: true
  imath_version:
    description: "Version of imath to build against"
    required: true
  global_cache_index:
    description: "Global cache index"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check required inputs
      shell: bash
      run: |
        [[ "${{ inputs.version }}" ]] || { echo "version input is empty" ; exit 1; }
        [[ "${{ inputs.imath_version }}" ]] || { echo "imath_version input is empty" ; exit 1; }
        [[ "${{ inputs.global_cache_index }}" ]] || { echo "global_cache_index input is empty" ; exit 1; }

    - name: Cache Alembic
      id: cache-alembic
      uses: actions/cache/restore@v4
      with:
        path: dependencies/alembic_install
        key: alembic-${{inputs.version}}-${{inputs.imath_version}}-${{runner.os}}-${{inputs.cpu}}-${{inputs.global_cache_index}}-3

    - name: Checkout Alembic
      if: steps.cache-alembic.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: alembic/alembic
        path: "./dependencies/alembic"
        ref: ${{inputs.version}}

    # https://github.com/alembic/alembic/issues/476
    - name: Patch Alembic rpath issue
      if: steps.cache-alembic.outputs.cache-hit != 'true' && inputs.version == '1.8.9'
      working-directory: ${{github.workspace}}/dependencies/alembic
      shell: bash
      run: patch -p1 < $GITHUB_ACTION_PATH/fix_cmake_rpath.patch

    - name: Setup Alembic
      if: steps.cache-alembic.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies
      shell: bash
      run: |
        mkdir alembic_build
        mkdir alembic_install

    - name: Configure Alembic
      if: steps.cache-alembic.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/alembic_build
      shell: bash
      run: >
        cmake ../alembic
        -DALEMBIC_LIB_INSTALL_DIR=${{ runner.os == 'Windows' && 'bin' || 'lib' }}
        -DALEMBIC_SHARED_LIBS=ON
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX:PATH=../alembic_install
        -DCMAKE_PREFIX_PATH:PATH=../install/
        -DUSE_BINARIES=OFF
        -DUSE_TESTS=OFF
        ${{ runner.os == 'macOS' && '-DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 -DCMAKE_MACOSX_RPATH=ON' || null }}
        ${{ runner.os == 'Windows' && '-Ax64 -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL' || null }}

    - name: Build Alembic
      if: steps.cache-alembic.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/alembic_build
      shell: bash
      run: cmake --build . --parallel 2 --target install --config Release

    - name: Copy to install
      working-directory: ${{github.workspace}}/dependencies/alembic_install
      shell: bash
      run: cp -r ./* ../install/

    - name: Save cache
      if: steps.cache-alembic.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        key: ${{ steps.cache-alembic.outputs.cache-primary-key }}
        path: dependencies/alembic_install
