name: 'Install Alembic Dependency'
description: 'Install Alembic Dependency using cache when possible'
inputs:
  os:
    description: 'OS to build on'
    required: false
    default: 'ubuntu-latest'
runs:
  using: "composite"
  steps:

    - name: Cache Alembic
      id: cache-alembic
      uses: actions/cache@v3
      with:
        path: dependencies/alembic_install
        key: alembic-v1.8.3-${{inputs.os}}-6

    - name: Checkout Alembic
      if: steps.cache-alembic.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: alembic/alembic
        path: './dependencies/alembic'
        ref: 1.8.3

    - name: Patch Alembic
      if: steps.cache-alembic.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/alembic
      shell: bash
      run: |
        patch -p1 < $GITHUB_ACTION_PATH/0001-use-install-rpath-for-Imath.patch
        patch -p1 < $GITHUB_ACTION_PATH/0002-Fix-an-issue-with-ALEMBIC_LIB_INSTALL_DIR.patch

    - name: Setup Alembic
      if: steps.cache-alembic.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies
      shell: bash
      run: |
        mkdir alembic_build
        mkdir alembic_install

    - name: Configure Alembic
      if: steps.cache-alembic.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/alembic_build
      shell: bash
      run: >
        cmake ../alembic
        -DALEMBIC_LIB_INSTALL_DIR=${{ inputs.os == 'windows-latest' && 'bin' || 'lib' }}
        -DALEMBIC_SHARED_LIBS=ON
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX:PATH=../alembic_install
        -DCMAKE_PREFIX_PATH:PATH=../install/
        -DUSE_BINARIES=OFF
        -DUSE_TESTS=OFF
        ${{ inputs.os == 'macos-latest' && '-DCMAKE_OSX_DEPLOYMENT_TARGET=10.15' || null }}
        ${{ inputs.os == 'windows-latest' && '-Ax64 -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL' || null }}

    - name: Build Alembic
      if: steps.cache-alembic.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/alembic_build
      shell: bash
      run: cmake --build . --parallel 2 --target install --config Release

    - name: Copy to install
      working-directory: ${{github.workspace}}/dependencies/alembic_install
      shell: bash
      run: cp -r ./* ../install/
