name: 'Install Alembic Dependency'
description: 'Install Alembic Dependency using cache when possible'

runs:
  using: "composite"
  steps:

    - name: Cache Alembic
      id: cache-alembic
      uses: actions/cache@v3
      with:
        path: dependencies/alembic_install
        key: alembic-v1.8.5-${{runner.os}}-0

    - name: Checkout Alembic
      if: steps.cache-alembic.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: alembic/alembic
        path: './dependencies/alembic'
        ref: 1.8.5

    - name: Setup Alembic
      if: steps.cache-alembic.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies
      shell: bash
      run: |
        mkdir alembic_build
        mkdir alembic_install

    - name: Configure Alembic
      if: steps.cache-alembic.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/alembic_build
      shell: bash
      run: >
        cmake ../alembic
        -DALEMBIC_LIB_INSTALL_DIR=${{ runner.os == 'Windows' && 'bin' || 'lib' }}
        -DALEMBIC_SHARED_LIBS=ON
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX:PATH=../alembic_install
        -DCMAKE_PREFIX_PATH:PATH=../install/
        -DUSE_BINARIES=OFF
        -DUSE_TESTS=OFF
        ${{ runner.os == 'macOS' && '-DCMAKE_OSX_DEPLOYMENT_TARGET=10.15' || null }}
        ${{ runner.os == 'Windows' && '-Ax64 -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL' || null }}

    - name: Build Alembic
      if: steps.cache-alembic.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/alembic_build
      shell: bash
      run: cmake --build . --parallel 2 --target install --config Release

    - name: Copy to install
      working-directory: ${{github.workspace}}/dependencies/alembic_install
      shell: bash
      run: cp -r ./* ../install/
