name: "Install MESA"
description: "Install MESA"
inputs:
  cpu:
    description: "CPU architecture to build for"
    required: false
    default: "x86_64"
  path:
    description: "Path to install MESA"
    required: false
    default: ""
  version:
    description: "MESA version to install"
    required: false
    default: "24.3.4"

runs:
  using: "composite"
  steps:
    - name: Cache MESA
      id: cache-mesa
      continue-on-error: true # https://github.com/actions/cache/issues/1754
      uses: actions/cache/restore@v5
      with:
        path: dependencies/mesa_install
        key: mesa-${{inputs.version}}-${{runner.os}}-${{inputs.cpu}}-14


    - name: Set up Python
      if: steps.cache-mesa.outputs.cache-hit != 'true'
      uses: actions/setup-python@v6
      with:
        python-version: 3.14

    - name: Setup MSVC (Windows)
      if: steps.cache-mesa.outputs.cache-hit != 'true' && runner.os == 'Windows'
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: x64

    - name: Remove Git link.exe (Windows)
      if: steps.cache-mesa.outputs.cache-hit != 'true' && runner.os == 'Windows'
      shell: bash
      run: rm $(which link.exe)

    - name: Install MESA build dependencies (Windows)
      if: steps.cache-mesa.outputs.cache-hit != 'true' && runner.os == 'Windows'
      shell: bash
      run: |
        python -m pip install meson mako packaging PyYAML
        choco install winflexbison3 llvm --no-progress -y
        echo "C:/Program Files/LLVM/bin" >> $GITHUB_PATH

    - name: Install MESA build dependencies (macOS/Linux)
      if: steps.cache-mesa.outputs.cache-hit != 'true' && runner.os != 'Windows'
      shell: bash
      run: python -m pip install meson mako packaging PyYAML

    - name: Install Bison (Linux)
      if: steps.cache-mesa.outputs.cache-hit != 'true' && runner.os == 'Linux'
      shell: bash
      run: apt-get install -y bison byacc flex pkg-config ninja-build python3-dev

    - name: Install LLVM (macOS)
      if: steps.cache-mesa.outputs.cache-hit != 'true' && runner.os == 'macOS'
      shell: bash
      run: |
        brew install llvm
        echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH

    - name: Checkout MESA
      if: steps.cache-mesa.outputs.cache-hit != 'true'
      shell: bash
      run: |
        git clone --recurse-submodules --depth 1 --branch mesa-${{inputs.version}} https://gitlab.freedesktop.org/mesa/mesa.git dependencies/mesa

    - name: Setup MESA
      if: steps.cache-mesa.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies
      shell: bash
      run: |
        mkdir mesa_build
        mkdir mesa_install

    - name: Configure MESA
      if: steps.cache-mesa.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies
      shell: bash
      run: >
        meson setup mesa_build mesa
        --prefix=$(pwd)/mesa_install
        --buildtype=release
        -Db_ndebug=true
        -Dosmesa=true
        -Dgallium-drivers=llvmpipe
        -Dvulkan-drivers=[]
        -Dopengl=true
        -Dgles1=disabled
        -Dgles2=disabled
        -Degl=disabled
        -Dglx=disabled
        -Dxlib-lease=disabled
        -Dxmlconfig=disabled
        -Dplatforms=[]
        -Dshared-glapi=enabled

    - name: Build MESA
      if: steps.cache-mesa.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/mesa_build
      shell: bash
      run: ninja -j2 install

    - name: Save cache
      if: steps.cache-mesa.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        key: ${{ steps.cache-mesa.outputs.cache-primary-key }}
        path: dependencies/mesa_install

    # Set the library name to be reused in the next step
    - name: Set library names
      if: runner.os == 'Windows'
      shell: bash
      run: |
        echo "MESA_LIBS=bin/*.dll" >> $GITHUB_ENV

    - name: Set library names
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo "MESA_LIBS=lib/*.so" >> $GITHUB_ENV

    - name: Set library names
      if: runner.os == 'macOS'
      shell: bash
      run: |
        echo "MESA_LIBS=lib/*.dylib" >> $GITHUB_ENV

    - name: Copy to specified path
      if: inputs.path != ''
      working-directory: ${{github.workspace}}/dependencies/mesa_install
      shell: bash
      run: |
        p=$(echo "${{inputs.path}}" | tr '\\' '/')
        for dir in $p; do
            cp $MESA_LIBS "$dir/"
        done
