name: Build And Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - master

jobs:
  build_and_test:
    if: github.event.pull_request.draft == false

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        vtk_version: [commit, v9.1.0, v9.0.0]

    runs-on: ${{matrix.os}}
    container: ${{ matrix.os == 'ubuntu-latest' && 'ghcr.io/f3d-app/f3d-ci' || null }}

    env:
      DISPLAY: :0

    steps:
    - name: Dependencies Dir
      working-directory: ${{github.workspace}}
      run: mkdir dependencies

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: 'source'
        fetch-depth: 0
        lfs: 'false'

    - name: Install OCCT dependency
      uses: ./source/.github/actions/occt-install-dep
      with:
        os: ${{matrix.os}}

    - name: Install Assimp dependency
      uses: ./source/.github/actions/assimp-install-dep
      with:
        os: ${{matrix.os}}

    - name: Install Imath dependency
      uses: ./source/.github/actions/imath-install-dep
      with:
        os: ${{matrix.os}}

    - name: Install Alembic dependency
      uses: ./source/.github/actions/alembic-install-dep
      with:
        os: ${{matrix.os}}

    - name: Install VTK dependency
      uses: ./source/.github/actions/vtk-install-dep
      with:
        vtk_version: ${{matrix.vtk_version}}
        vtk_sha_file: ./source/.github/actions/vtk-install-dep/vtk_commit_sha
        os: ${{matrix.os}}

    - name: Set LFS env var
      working-directory: ${{github.workspace}}/source
      shell: bash
      run: echo "LFS_SHA=$(git log -n 1 --pretty=format:%H -- testing/data/ testing/baselines/)" >> $GITHUB_ENV

    - name: Copy LFS Data
      uses: ./source/.github/actions/lfs-copy
      with:
        lfs_sha: ${{env.LFS_SHA}}

    - name: Setup Directories
      working-directory: ${{github.workspace}}
      run: |
         mkdir build
         mkdir install

    # pwd seems necessary for OpenCASCADE and Assimp for some reasons
    - name: Configure
      working-directory: ${{github.workspace}}/build
      run: >
        cmake ../source
        -DBUILD_TESTING=ON
        -DCMAKE_INSTALL_PREFIX:PATH=../install
        -DF3D_STRICT_BUILD=ON
        -DF3D_MODULE_OCCT=ON
        -DF3D_MODULE_ASSIMP=ON
        -DF3D_MODULE_ALEMBIC=ON
        -DCMAKE_BUILD_TYPE=Release
        -DVTK_DIR:PATH=../dependencies/vtk_install/lib/cmake/vtk
        -Dassimp_DIR:PATH=$(pwd)/../dependencies/assimp_install/lib/cmake/assimp-5.1
        -DAlembic_DIR:PATH=$(pwd)/../dependencies/alembic_install/lib/cmake/Alembic
        -DImath_DIR:PATH=$(pwd)/../dependencies/imath_install/lib/cmake/Imath
        -DF3D_INSTALL_DEFAULT_CONFIGURATION_FILE=ON
        ${{ matrix.os == 'windows-latest' && '-Ax64 -DF3D_INSTALL_SDK=ON -DF3D_WINDOWS_GUI=ON -DOpenCASCADE_DIR:PATH=$(pwd)/../dependencies/occt_install/cmake/ -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded' || null }}
        ${{ matrix.os == 'macos-latest' && '-DF3D_MACOS_BUNDLE=ON -DOpenCASCADE_DIR:PATH=$(pwd)/../dependencies/occt_install/lib/cmake/opencascade' || null }}
        ${{ matrix.os == 'ubuntu-latest' && '-DF3D_INSTALL_SDK=ON -DOpenCASCADE_DIR:PATH=$(pwd)/../dependencies/occt_install/lib/cmake/opencascade -DF3D_INSTALL_DEFAULT_CONFIGURATION_FILE_IN_PREFIX=ON -DF3D_GENERATE_MAN=ON -DF3D_INSTALL_MIME_TYPES_FILE=ON -DF3D_INSTALL_THUMBNAILER_FILES=ON -DF3D_ENABLE_LONG_TIMEOUT_TESTS=ON' || null }}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --parallel 2 --config Release

    - name: Run Xvfb ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: Xvfb $DISPLAY -screen 0 1280x1024x24 &

    - name: Install Mesa windows
      shell: cmd
      if: matrix.os == 'windows-latest'
      working-directory: ${{github.workspace}}/dependencies/
      run: |
        mkdir mesa
        cd mesa
        curl.exe -L --output mesa.7z --url https://github.com/pal1000/mesa-dist-win/releases/download/20.3.2/mesa3d-20.3.2-release-msvc.7z
        "C:\Program Files\7-Zip\7z.exe" x mesa.7z
        cp x64\opengl32.dll ..\..\build\bin\Release\
        cp x64\libglapi.dll ..\..\build\bin\Release\

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Release -j 2 --output-on-failure || ctest -C Release -j 1 --rerun-failed

    - name: Install
      working-directory: ${{github.workspace}}/build
      run: cmake --install .

    - name: Check Install ubuntu
      if: matrix.os == 'ubuntu-latest'
      working-directory: ${{github.workspace}}/install
      run: ./bin/f3d ../source/testing/data/suzanne.obj --output=../output.png

    - name: Check Install windows
      if: matrix.os == 'windows-latest'
      working-directory: ${{github.workspace}}/install
      run: |
        cp ..\dependencies\mesa\x64\opengl32.dll .\bin\
        cp ..\dependencies\mesa\x64\libglapi.dll .\bin\
        .\bin\f3d.exe ..\source\testing\data\suzanne.obj --output=..\output.png

    - name: Check Install macos
      if: matrix.os == 'macos-latest'
      working-directory: ${{github.workspace}}/install
      run: ./f3d.app/Contents/MacOS/f3d ../source/testing/data/suzanne.obj --output=../output.png

    - name: Check SDK
      if: matrix.os != 'macos-latest'
      working-directory: ${{github.workspace}}
      run: |
        cmake -Df3d_DIR:PATH=$(pwd)/install/lib/cmake/f3d -B test_sdk source/.github/test_sdk 
        cmake --build test_sdk

    - name: Setup NSIS
      if: matrix.os == 'windows-latest'
      working-directory: ${{github.workspace}}
      run: cp source\.github\nsis\FileAssociation.nsh "C:/Program Files (x86)/NSIS/Include"

    - name: Packaging
      working-directory: ${{github.workspace}}/build
      run: cpack

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ./build/f3d-*
        name: f3d-${{matrix.os}}-${{matrix.vtk_version}}
