name: Build cache preheating

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - master
      - release
    paths-ignore:
      - "doc/**"
      - "_config.yml"

jobs:
  #----------------------------------------------------------------------------
  # Trigger a cache preheating workflow
  #----------------------------------------------------------------------------
  build_cache_preheating:
    name: Build docker images
    if: contains(github.event.pull_request.labels.*.name, 'ci:cache')
    runs-on: ubuntu-latest
    steps:
      # This require a F3D_CACHE_CI_DISPATCH secret contain a PAT with read and write admin access
      - name: Trigger docker images build
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: f3d-app
          repo: f3d
          github_token: ${{ secrets.F3D_CACHE_CI_DISPATCH }}
          workflow_file_name: cache-preheating.yml
          wait_interval: 60
          client_payload: '{"repo": "${{github.event.pull_request.head.repo.full_name}}"}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true

      - uses: marocchino/sticky-pull-request-comment@v3.0.4
        if: ${{env.F3D_DOCKER_IMAGE_AVAILABLE == '1'}}
        with:
          message: Caches have been generated/checked
