on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - master
      - release
name: Build docker images
jobs:

#----------------------------------------------------------------------------
# Detect checkboxes are checked
#----------------------------------------------------------------------------
  detect_checkboxes:
    name: Detect Checkboxes
    runs-on: ubuntu-latest
    outputs:
      checked: ${{ steps.detect.outputs.checked }}
      unchecked: ${{ steps.detect.outputs.unchecked }}

    permissions:
      pull-requests: write

    steps:
      - name: Checkbox Trigger
        id: detect
        uses: AhmedBaset/checklist@3
        with:
          token: ${{ github.token }}

      - name: list changes
        run: |
          echo "checked=${{ steps.detect.outputs.checked }}"
          echo "unchecked=${{ steps.detect.outputs.unchecked }}"

#----------------------------------------------------------------------------
# Default versions: Set default version for all dependencies
#----------------------------------------------------------------------------
  default_versions:
    runs-on: ubuntu-22.04
    container: ghcr.io/f3d-app/f3d-ci
    name: Set default versions
    needs: detect_checkboxes
    if: ${{ (contains(needs.detect_checkboxes.outputs.checked, 'CI')) || (github.ref == 'refs/heads/master') }}
    outputs:
      alembic_version: ${{ steps.set_default_versions.outputs.alembic_version }}
      alembic_min_version: ${{ steps.set_default_versions.outputs.alembic_min_version }}
      assimp_version: ${{ steps.set_default_versions.outputs.assimp_version }}
      assimp_min_version: ${{ steps.set_default_versions.outputs.assimp_min_version }}
      draco_version: ${{ steps.set_default_versions.outputs.draco_version }}
      draco_min_version: ${{ steps.set_default_versions.outputs.draco_min_version }}
      occt_version: ${{ steps.set_default_versions.outputs.occt_version }}
      occt_min_version: ${{ steps.set_default_versions.outputs.occt_min_version }}
      openexr_version: ${{ steps.set_default_versions.outputs.openexr_version }}
      openexr_min_version: ${{ steps.set_default_versions.outputs.openexr_min_version }}
      openvdb_version: ${{ steps.set_default_versions.outputs.openvdb_version }}
      openvdb_min_version: ${{ steps.set_default_versions.outputs.openvdb_min_version }}
      pybind11_version: ${{ steps.set_default_versions.outputs.pybind11_version }}
      pybind11_min_version: ${{ steps.set_default_versions.outputs.pybind11_min_version }}
      python_version: ${{ steps.set_default_versions.outputs.python_version }}
      python_min_version: ${{ steps.set_default_versions.outputs.python_min_version }}
      usd_version: ${{ steps.set_default_versions.outputs.usd_version }}
      usd_min_version: ${{ steps.set_default_versions.outputs.usd_min_version }}
      java_version: ${{ steps.set_default_versions.outputs.java_version }}
      java_min_version: ${{ steps.set_default_versions.outputs.java_min_version }}
      vtk_commit_sha: ${{ steps.set_default_versions.outputs.vtk_commit_sha }}
      timestamp: ${{ steps.set_default_versions.outputs.timestamp }}

    steps:

    - uses: actions/checkout@v4
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
        path: 'source'
        fetch-depth: 1
        lfs: false

    - name: Set default versions
      id: set_default_versions
      uses: f3d-app/default-versions-action@main
      with:
        file: ./source/.github/workflows/versions.json

#----------------------------------------------------------------------------
# Check android/wasm docker images
#----------------------------------------------------------------------------
  check_docker_images:
    needs: default_versions

    runs-on: ubuntu-22.04

    steps:

    # {0} is needed to avoid exit on fail
    - name: Check docker images exists
      shell: bash {0}
      working-directory: ${{github.workspace}}
      run: |
         docker manifest inspect ghcr.io/f3d-app/f3d-wasm:${{needs.default_versions.outputs.timestamp}}
         res=$?
         docker manifest inspect ghcr.io/f3d-app/f3d-android-armeabi-v7a:${{needs.default_versions.outputs.timestamp}}
         [ $? -eq 0 ] && [ $res -eq 0 ] || res=$?
         docker manifest inspect ghcr.io/f3d-app/f3d-android-arm64-v8a:${{needs.default_versions.outputs.timestamp}}
         [ $? -eq 0 ] && [ $res -eq 0 ] || res=$?
         docker manifest inspect ghcr.io/f3d-app/f3d-android-x86:${{needs.default_versions.outputs.timestamp}}
         [ $? -eq 0 ] && [ $res -eq 0 ] || res=$?
         docker manifest inspect ghcr.io/f3d-app/f3d-android-x86_64:${{needs.default_versions.outputs.timestamp}}
         [ $? -eq 0 ] && [ $res -eq 0 ] || res=$?
         echo "F3D_DOCKER_IMAGE_AVAILABLE=$res" >> $GITHUB_ENV

    # This require a F3D_DOCKER_CI_DISPATCH secret contain a PAT with read and write admin access
    - name: Trigger docker images build
      env:
          secret: ${{ secrets.F3D_DOCKER_CI_DISPATCH }}
      if: ${{env.F3D_DOCKER_IMAGE_AVAILABLE == '1' && env.secret != '' }}
      uses: convictional/trigger-workflow-and-wait@v1.6.5
      with:
        owner: f3d-app
        repo: f3d-docker-images
        github_token: ${{ secrets.F3D_DOCKER_CI_DISPATCH }}
        workflow_file_name: build_docker_image.yml
        wait_interval: 60
        client_payload: '{"versions_file_url": "https://raw.githubusercontent.com/${{github.event.pull_request.head.repo.full_name}}/${{github.event.pull_request.head.ref}}/.github/workflows/versions.json"}'
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true

    - name: Error out when unable to build docker images
      env:
          secret: ${{ secrets.F3D_DOCKER_CI_DISPATCH }}
      if: ${{env.F3D_DOCKER_IMAGE_AVAILABLE == '1' && env.secret == '' }}
      uses: actions/github-script@v3
      with:
