name: Cache preheating

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - master
      - release
    paths-ignore:
      - "doc/**"
      - "_config.yml"

concurrency:
  group: "${{ github.workflow }}-${{  github.ref_name }}"
  cancel-in-progress: true

jobs:
  #----------------------------------------------------------------------------
  # Cache preheating all dependencies
  #----------------------------------------------------------------------------
  cache_preheating_dependencies:
    name: Preheat dependency caches
    if: contains(github.event.pull_request.labels.*.name, 'ci:cache')
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-15, macos-15-intel]
        build_type: [standard]
        include:
          - mindeps_label: no-mindeps
          - build_type: mindeps
            os: ubuntu-24.04
            mindeps_label: mindeps

    runs-on: ${{matrix.os}}
    container: ${{ matrix.os == 'ubuntu-24.04' && 'ghcr.io/f3d-app/f3d-ci' || null }}
    env:
      CMAKE_POLICY_VERSION_MINIMUM: 3.5

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          path: "source"
          fetch-depth: 1
          lfs: false

      - name: Generic Dependencies
        uses: ./source/.github/actions/generic-dependencies
        with:
          versions_file: ./source/.github/workflows/versions.json
          mindeps_label: ${{matrix.mindeps_label}}
          cpu: ${{ matrix.os == 'macos-15' && 'arm64' || 'x86_64' }}

  #----------------------------------------------------------------------------
  # Cache preheating VTK
  #----------------------------------------------------------------------------
  cache_preheating_vtk:
    needs: [cache_preheating_dependencies]
    name: Preheat VTK dependency caches
    if: contains(github.event.pull_request.labels.*.name, 'ci:cache')
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-15, macos-15-intel]
        vtk_version: [commit, v9.6.1, v9.5.2, v9.4.2]
        build_type: [standard]
        include:
          - optdeps_label: optdeps
          - mindeps_label: no-mindeps
          - build_type: mindeps
            os: ubuntu-24.04
            vtk_version: commit
            optdeps_label: optdeps
            mindeps_label: mindeps
          - build_type: no-optdeps
            os: ubuntu-24.04
            vtk_version: commit
            optdeps_label: no-optdeps
            mindeps_label: no-mindeps

    runs-on: ${{matrix.os}}
    container: ${{ matrix.os == 'ubuntu-24.04' && 'ghcr.io/f3d-app/f3d-ci' || null }}

    env:
      CMAKE_POLICY_VERSION_MINIMUM: 3.5

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          path: "source"
          fetch-depth: 1
          lfs: false

      - name: VTK Dependencies (already cached)
        uses: ./source/.github/actions/vtk-dependencies
        with:
          versions_file: ./source/.github/workflows/versions.json
          optdeps_label: ${{matrix.optdeps_label}}
          mindeps_label: ${{matrix.mindeps_label}}
          cpu: ${{ matrix.os == 'macos-15' && 'arm64' || 'x86_64' }}

      - name: Cache VTK
        uses: ./source/.github/actions/vtk-install-dep
        with:
          versions_file: ./source/.github/workflows/versions.json
          optdeps_label: ${{matrix.optdeps_label}}
          mindeps_label: ${{matrix.mindeps_label}}
          cpu: ${{ matrix.os == 'macos-15' && 'arm64' || 'x86_64' }}
          vtk_version: ${{matrix.vtk_version}}
