on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - master
      - release
name: Cache preheating
jobs:
  #----------------------------------------------------------------------------
  # Cache preheating
  #----------------------------------------------------------------------------
  cache_preheating:
    name: Cache Preheating
    runs-on: ubuntu-22.04
    container: ghcr.io/f3d-app/f3d-ci
    env:
      CMAKE_POLICY_VERSION_MINIMUM: 3.5

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          path: "source"
          fetch-depth: 1
          lfs: false

      - name: Dependencies Dir
        shell: bash
        working-directory: ${{github.workspace}}
        run: |
          mkdir dependencies
          cd dependencies
          mkdir install

      - name: VTK Dependencies
        uses: ./source/.github/actions/vtk-dependencies
        with:
          versions_file: ./source/.github/workflows/versions.json
          cpu: x86_64

      - name: Install Raytracing Dependencies
        uses: ./source/.github/actions/ospray-sb-install-dep
        with:
          versions_file: .github/workflows/versions.json
          cpu: x86_64

      - name: Install F3D dependencies
        uses: ./source/.github/actions/f3d-dependencies
        with:
          versions_file: .github/workflows/versions.json
          cpu: x86_64
