on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - master
      - release
name: Cache preheating
jobs:
  #----------------------------------------------------------------------------
  # Cache preheating
  #----------------------------------------------------------------------------
  cache_preheating:
    name: Cache Preheating
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 1
          lfs: false

      - name: Dependencies Dir
        shell: bash
        working-directory: ${{github.workspace}}
        run: |
          mkdir dependencies
          cd dependencies
          mkdir install

      - name: Install sqlite
        uses: ./.github/actions/sqlite-install-dep
        with:
          cpu: x86_64
          csb_version: 08be462f7fa9816f881dbb93eacb2e287f319208
          global_cache_index: 0
