name: Cancel

on: push

jobs:
  cancel:
   name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
    - name: cancel running workflows
      uses: everphone-gmbh/cancel-previous-workflows@v5
      env:
        GITHUB_TOKEN: ${{ github.token }}
 
