name: clang-tidy Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Clang Tidy Check
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: 'source'
        fetch-depth: 0
        lfs: 'false'

    - name: Dependencies Dir
      working-directory: ${{github.workspace}}
      run: mkdir dependencies

    - name: Install OCCT dependency
      uses: ./source/.github/actions/occt-install-dep

    - name: Install Assimp dependency
      uses: ./source/.github/actions/assimp-install-dep

    - name: Install Imath dependency
      uses: ./source/.github/actions/imath-install-dep

    - name: Install Alembic dependency
      uses: ./source/.github/actions/alembic-install-dep

    - name: Install VTK dependency
      uses: ./source/.github/actions/vtk-install-dep
      with:
        vtk_sha_file: ./source/.github/actions/vtk-install-dep/vtk_commit_sha

    - name: Setup Directories
      working-directory: ${{github.workspace}}
      run: mkdir build

    # pwd seems necessary for OpenCASCADE and Assimp for some reasons
    # coverage build is done in source as it seems to be required for codecov
    - name: Configure
      working-directory: ${{github.workspace}}/build
      run: >
        cmake ./
        -DBUILD_TESTING=ON
        -DF3D_ENABLE_LONG_TIMEOUT_TESTS=ON
        -DF3D_STRICT_BUILD=ON
        -DF3D_MODULE_OCCT=ON
        -DF3D_MODULE_ASSIMP=ON
        -DF3D_MODULE_ALEMBIC=ON
        -DCMAKE_BUILD_TYPE=Release
        -DVTK_DIR:PATH=../dependencies/vtk_install/lib/cmake/vtk
        -DOpenCASCADE_DIR:PATH=$(pwd)/../dependencies/occt_install/lib/cmake/opencascade
        -Dassimp_DIR:PATH=$(pwd)/../dependencies/assimp_install/lib/cmake/assimp-5.1
        -DAlembic_DIR:PATH=$(pwd)/../dependencies/alembic_install/lib/cmake/Alembic
        -DImath_DIR:PATH=$(pwd)/../dependencies/imath_install/lib/cmake/Imath
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --parallel 2 --config Release

    - uses: ZedThree/clang-tidy-review@v0.7.0
      id: review
      with:
        build_dir: ./build

    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1
