name: Coverage

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - master

jobs:
  coverage:
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest
    container: ghcr.io/f3d-app/f3d-ci

    env:
      DISPLAY: :0

    steps:
    - name: Dependencies Dir
      working-directory: ${{github.workspace}}
      run: mkdir dependencies

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: 'source'
        fetch-depth: 0
        lfs: 'false'

    - name: Install OCCT dependency
      uses: ./source/.github/actions/occt-install-dep
      with:
        os: ubuntu-latest

    - name: Install Assimp dependency
      uses: ./source/.github/actions/assimp-install-dep
      with:
        os: ubuntu-latest

    - name: Install Imath dependency
      uses: ./source/.github/actions/imath-install-dep
      with:
        os: ubuntu-latest

    - name: Install Alembic dependency
      uses: ./source/.github/actions/alembic-install-dep
      with:
        os: ubuntu-latest

    - name: Install VTK dependency
      uses: ./source/.github/actions/vtk-install-dep
      with:
        vtk_version: commit
        vtk_sha_file: ./source/.github/actions/vtk-install-dep/vtk_commit_sha
        os: ubuntu-latest

    - name: Set LFS env var
      working-directory: ${{github.workspace}}/source
      shell: bash
      run: echo "LFS_SHA=$(git log -n 1 --pretty=format:%H -- testing/data/ testing/baselines/)" >> $GITHUB_ENV

    - name: Copy LFS Data
      uses: ./source/.github/actions/lfs-copy
      with:
        lfs_sha: ${{env.LFS_SHA}}

    # pwd seems necessary for OpenCASCADE and Assimp for some reasons
    # coverage build is done in source as it seems to be required for codecov
    - name: Configure
      working-directory: ${{github.workspace}}/source
      run: >
        cmake ./
        -DBUILD_TESTING=ON
        -DF3D_ENABLE_LONG_TIMEOUT_TESTS=ON
        -DF3D_STRICT_BUILD=ON
        -DF3D_MODULE_OCCT=ON
        -DF3D_MODULE_ASSIMP=ON
        -DF3D_MODULE_ALEMBIC=ON
        -DCMAKE_BUILD_TYPE=Release
        -DVTK_DIR:PATH=../dependencies/vtk_install/lib/cmake/vtk
        -DOpenCASCADE_DIR:PATH=$(pwd)/../dependencies/occt_install/lib/cmake/opencascade
        -Dassimp_DIR:PATH=$(pwd)/../dependencies/assimp_install/lib/cmake/assimp-5.1
        -DAlembic_DIR:PATH=$(pwd)/../dependencies/alembic_install/lib/cmake/Alembic
        -DImath_DIR:PATH=$(pwd)/../dependencies/imath_install/lib/cmake/Imath
        -DF3D_COVERAGE=ON

    - name: Build
      working-directory: ${{github.workspace}}/source
      run: cmake --build . --parallel 2 --config Release

    - name: Run Xvfb
      run: Xvfb $DISPLAY -screen 0 1280x1024x24 &

    - name: Test
      working-directory: ${{github.workspace}}/source
      run: ctest -C Release -j 2 --output-on-failure || ctest -C Release -j 1 --rerun-failed

    - name: Generate XML Coverage
      working-directory: ${{github.workspace}}/source
      run: |
        lcov --base-directory . --directory . -c -o coverage.info
        lcov --remove coverage.info "*/dependencies/*" -o coverage.info
        lcov --remove coverage.info "*/cxxopts.hpp" -o coverage.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ${{github.workspace}}/source/coverage.info
