on: issue_comment
name: Labelize
jobs:
  #----------------------------------------------------------------------------
  # Labelize
  #----------------------------------------------------------------------------
  labelize:
    name: Labelize
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}

    steps:
      - name: Comment on PR
        if: contains(github.event.comment.body, '\label ci:')
        shell: bash
        run: |
          label=$(cut -d " " -f2- <<< "${{ github.event.comment.body }}")
          gh issue edit ${{ github.event.issue.number }} --add-label "$label"
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.F3D_CI_LABEL }}
