on: issue_comment
name: Labelize
jobs:
  #----------------------------------------------------------------------------
  # Labelize
  #----------------------------------------------------------------------------
  labelize:
    name: Labelize
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.F3D_CI_LABEL }}

    steps:
      - name: Analyze comment
        if: contains(github.event.comment.body, '\ci')
        shell: bash
        run: |
          label="${{github.event.comment.body}}"
          label=${label#* }
          label=${label%% *}
          echo "F3D_LABEL_COMMENT=$label" >> $GITHUB_ENV

      - name: Add label on PR
        if: ${{!contains(env.F3D_LABEL_COMMENT, '-')}}
        shell: bash
        run: gh issue edit ${{ github.event.issue.number }} --add-label "ci:${{env.F3D_LABEL_COMMENT}}"

      - name: Remove label on PR
        if: contains(env.F3D_LABEL_COMMENT, '-')
        shell: bash
        run: |
          label="${{env.F3D_LABEL_COMMENT}}"
          label=${label#*-}
          gh issue edit ${{ github.event.issue.number }} --remove-label "ci:$label"

      - name: Add ack reaction
        uses: GrantBirki/comment@v2.1.1
        with:
          comment-id: ${{ github.event.issue.id }}
          reactions: eyes

      - name: Create comment for invalid command
        if: failure()
        uses: GrantBirki/comment@v2.1.1
        with:
          body: Invalid ci command ${{env.F3D_LABEL_COMMENT}}
