name: 'Install VTK Android Dependency'
description: 'Install VTK Android Dependency using cache when possible'
inputs:
  arch:
    description: 'Android CPU architecture'
    required: true
  api_level:
    description: 'Android API level'
    required: false
    default: '27'
  vtk_version:
    description: 'VTK version'
    required: false
    default: 'commit'
  vtk_sha_file:
    description: 'VTK SHA file'
    required: false
    default: ''

runs:
  using: "composite"
  steps:

    - name: Check required inputs
      shell: bash
      run: |
        [[ "${{ inputs.arch }}" ]] || { echo "arch input is empty" ; exit 1; }

    - name: Recover VTK Short SHA from file
      if: |
        steps.cache-vtk.outputs.cache-hit != 'true' &&
        inputs.vtk_version == 'commit'
      working-directory: ${{github.workspace}}
      shell: bash
      run: echo "VTK_SHA_OR_TAG=$(<${{ inputs.vtk_sha_file }})" >> $GITHUB_ENV

    - name: Copy VTK version to env var
      if: |
        steps.cache-vtk.outputs.cache-hit != 'true' &&
        inputs.vtk_version != 'commit'
      working-directory: ${{github.workspace}}
      shell: bash
      run: echo "VTK_SHA_OR_TAG=${{inputs.vtk_version}}" >> $GITHUB_ENV

    - name: Cache VTK
      id: cache-vtk
      uses: actions/cache@v4
      with:
        path: dependencies/vtk_build
        key: vtk-android-${{env.VTK_SHA_OR_TAG}}-${{inputs.api_level}}-${{inputs.arch}}-0

    - name: Setup VTK
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies
      shell: bash
      run: mkdir vtk_build

    - name: Checkout VTK
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: Kitware/VTK
        submodules: true
        path: './dependencies/vtk'
        ref: ${{env.VTK_SHA_OR_TAG}}

    - name: Configure VTK
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/vtk_build
      shell: bash
      run: >
        cmake ../vtk
        -DANDROID_ARCH_ABI=${{inputs.arch}}
        -DANDROID_NATIVE_API_LEVEL=${{inputs.api_level}}
        -DANDROID_NDK=$(pwd)/../../android-ndk
        -DCMAKE_BUILD_TYPE=Release
        -DVTK_ANDROID_BUILD=ON

    - name: Build VTK
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/vtk_build
      shell: bash
      run: cmake --build . --parallel 2
