name: 'Install VTK Android Dependency'
description: 'Install VTK Android Dependency using cache when possible'
inputs:
  arch:
    description: 'Android CPU architecture'
    required: true
  api_level:
    description: 'Android API level'
    required: false
    default: '27'
  vtk_version:
    description: 'VTK version'
    required: true

runs:
  using: "composite"
  steps:

    - name: Check required inputs
      shell: bash
      run: |
        [[ "${{ inputs.arch }}" ]] || { echo "arch input is empty" ; exit 1; }
        [[ "${{ inputs.vtk_version }}" ]] || { echo "vtk_version input is empty" ; exit 1; }

    - name: Cache VTK
      id: cache-vtk
      uses: actions/cache/restore@v4
      with:
        path: dependencies/vtk_build
        key: vtk-android-${{ inputs.vtk_version }}-${{inputs.api_level}}-${{inputs.arch}}-1

    - name: Setup VTK
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies
      shell: bash
      run: mkdir vtk_build

    - name: Checkout VTK
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: Kitware/VTK
        submodules: true
        path: './dependencies/vtk'
        ref: ${{env.VTK_SHA_OR_TAG}}

    - name: Configure VTK
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/vtk_build
      shell: bash
      run: >
        cmake ../vtk
        -DANDROID_ARCH_ABI=${{inputs.arch}}
        -DANDROID_NATIVE_API_LEVEL=${{inputs.api_level}}
        -DANDROID_NDK=$(pwd)/../../android-ndk
        -DCMAKE_BUILD_TYPE=Release
        -DVTK_ANDROID_BUILD=ON

    - name: Build VTK
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/dependencies/vtk_build
      shell: bash
      run: cmake --build . --parallel 2

    - name: Save cache
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        key: ${{ steps.cache-vtk.outputs.cache-primary-key }}
        path: dependencies/vtk_build
